export { rentQuestions } from "./rent";
export { propertyQuestions } from "./property";
export { consumerQuestions } from "./consumer";
export { employmentQuestions } from "./employment";
export { familyQuestions } from "./family";
export { ecommerceQuestions } from "./ecommerce";
export { cyberFraudQuestions } from "./cyber-fraud";
export { chequeBounceQuestions } from "./cheque-bounce";
export { policeFirQuestions } from "./police-fir";
