import type { BilingualText } from "@/types";

export interface TemplateField {
  id: string;
  label: BilingualText;
  type: "text" | "date" | "textarea" | "number";
  placeholder?: string;
  required: boolean;
}

export interface DocumentTemplate {
  id: string;
  title: BilingualText;
  description: BilingualText;
  category: string;
  fields: TemplateField[];
  template: BilingualText; // text with {{field_id}} placeholders
}

export const documentTemplates: DocumentTemplate[] = [
  {
    id: "rent-agreement",
    title: { en: "Rent Agreement (11 Months)", hi: "किराया अनुबंध (11 महीने)" },
    description: { en: "Standard residential rent agreement template.", hi: "मानक आवासीय किराया अनुबंध टेम्पलेट।" },
    category: "rent",
    fields: [
      { id: "landlord_name", label: { en: "Landlord Name", hi: "मकान मालिक का नाम" }, type: "text", required: true },
      { id: "tenant_name", label: { en: "Tenant Name", hi: "किरायेदार का नाम" }, type: "text", required: true },
      { id: "property_address", label: { en: "Property Address", hi: "संपत्ति का पता" }, type: "textarea", required: true },
      { id: "monthly_rent", label: { en: "Monthly Rent (₹)", hi: "मासिक किराया (₹)" }, type: "number", required: true },
      { id: "security_deposit", label: { en: "Security Deposit (₹)", hi: "सुरक्षा जमा (₹)" }, type: "number", required: true },
      { id: "start_date", label: { en: "Start Date", hi: "प्रारंभ तिथि" }, type: "date", required: true },
      { id: "notice_period", label: { en: "Notice Period (months)", hi: "नोटिस अवधि (महीने)" }, type: "number", placeholder: "1", required: true },
    ],
    template: {
      en: `RENT AGREEMENT

This Rent Agreement is made on {{start_date}} between:

LANDLORD: {{landlord_name}} (hereinafter referred to as "the Landlord")
TENANT: {{tenant_name}} (hereinafter referred to as "the Tenant")

For the property located at: {{property_address}}

TERMS AND CONDITIONS:

1. DURATION: This agreement is for a period of 11 (eleven) months commencing from {{start_date}}.

2. RENT: The Tenant shall pay a monthly rent of ₹{{monthly_rent}} (Rupees {{monthly_rent}} only), payable on or before the 5th of each month.

3. SECURITY DEPOSIT: The Tenant has paid a security deposit of ₹{{security_deposit}} (Rupees {{security_deposit}} only), refundable at the time of vacating, after deducting any damages.

4. NOTICE PERIOD: Either party must give {{notice_period}} month(s) written notice before vacating or terminating.

5. MAINTENANCE: Minor repairs up to ₹500 shall be borne by the Tenant. Major structural repairs by the Landlord.

6. USE: The premises shall be used for residential purposes only.

7. SUBLETTING: The Tenant shall not sublet the premises without written consent of the Landlord.

IN WITNESS WHEREOF, the parties have signed this agreement on the date mentioned above.


LANDLORD: ___________________     TENANT: ___________________
Name: {{landlord_name}}              Name: {{tenant_name}}

WITNESS 1: ___________________    WITNESS 2: ___________________

---
Template generated by NyayCheck. Please consult a lawyer before using.`,
      hi: `किराया अनुबंध

यह किराया अनुबंध {{start_date}} को निम्नलिखित पक्षों के बीच किया गया है:

मकान मालिक: {{landlord_name}} (इसके बाद "मकान मालिक" के रूप में संदर्भित)
किरायेदार: {{tenant_name}} (इसके बाद "किरायेदार" के रूप में संदर्भित)

संपत्ति का पता: {{property_address}}

नियम और शर्तें:

1. अवधि: यह अनुबंध {{start_date}} से 11 (ग्यारह) महीने की अवधि के लिए है।

2. किराया: किरायेदार प्रत्येक माह की 5 तारीख तक ₹{{monthly_rent}} मासिक किराया देगा।

3. सुरक्षा जमा: किरायेदार ने ₹{{security_deposit}} सुरक्षा जमा का भुगतान किया है, जो मकान खाली करते समय नुकसान की कटौती के बाद वापस किया जाएगा।

4. नोटिस अवधि: किसी भी पक्ष को खाली करने या समाप्त करने से {{notice_period}} महीने पहले लिखित नोटिस देना होगा।

5. रखरखाव: ₹500 तक की मामूली मरम्मत किरायेदार द्वारा। बड़ी संरचनात्मक मरम्मत मकान मालिक द्वारा।

6. उपयोग: परिसर केवल आवासीय उद्देश्य के लिए उपयोग किया जाएगा।


मकान मालिक: ___________________     किरायेदार: ___________________
नाम: {{landlord_name}}                   नाम: {{tenant_name}}

गवाह 1: ___________________          गवाह 2: ___________________

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "legal-notice",
    title: { en: "General Legal Notice", hi: "सामान्य कानूनी नोटिस" },
    description: { en: "Send a formal legal notice before taking legal action.", hi: "कानूनी कार्रवाई से पहले औपचारिक कानूनी नोटिस भेजें।" },
    category: "legal",
    fields: [
      { id: "sender_name", label: { en: "Your Name", hi: "आपका नाम" }, type: "text", required: true },
      { id: "sender_address", label: { en: "Your Address", hi: "आपका पता" }, type: "textarea", required: true },
      { id: "recipient_name", label: { en: "Recipient Name", hi: "प्राप्तकर्ता का नाम" }, type: "text", required: true },
      { id: "recipient_address", label: { en: "Recipient Address", hi: "प्राप्तकर्ता का पता" }, type: "textarea", required: true },
      { id: "subject", label: { en: "Subject", hi: "विषय" }, type: "text", required: true },
      { id: "facts", label: { en: "Facts of the matter", hi: "मामले के तथ्य" }, type: "textarea", required: true },
      { id: "demand", label: { en: "Your demand / relief sought", hi: "आपकी मांग / चाही गई राहत" }, type: "textarea", required: true },
      { id: "deadline_days", label: { en: "Response deadline (days)", hi: "जवाब की समय सीमा (दिन)" }, type: "number", placeholder: "15", required: true },
    ],
    template: {
      en: `LEGAL NOTICE

Date: {{today}}

To,
{{recipient_name}}
{{recipient_address}}

From,
{{sender_name}}
{{sender_address}}

Subject: {{subject}}

NOTICE

Under instructions from my client {{sender_name}}, I hereby serve upon you the following legal notice:

FACTS:
{{facts}}

DEMAND:
{{demand}}

You are hereby called upon to comply with the above demand within {{deadline_days}} days of receipt of this notice, failing which my client shall be constrained to initiate appropriate legal proceedings against you, at your risk, cost, and consequences.

This notice is sent without prejudice to any other rights and remedies available to my client under law.

{{sender_name}}

---
Template generated by NyayCheck. Consult a lawyer before sending.`,
      hi: `कानूनी नोटिस

दिनांक: {{today}}

सेवा में,
{{recipient_name}}
{{recipient_address}}

प्रेषक,
{{sender_name}}
{{sender_address}}

विषय: {{subject}}

नोटिस

अपने मुवक्किल {{sender_name}} के निर्देशानुसार, मैं आपको निम्नलिखित कानूनी नोटिस भेज रहा/रही हूं:

तथ्य:
{{facts}}

मांग:
{{demand}}

आपको इस नोटिस की प्राप्ति के {{deadline_days}} दिनों के भीतर उपरोक्त मांग का अनुपालन करने का आह्वान किया जाता है, अन्यथा मेरे मुवक्किल आपके जोखिम, लागत और परिणामों पर उचित कानूनी कार्यवाही शुरू करने के लिए बाध्य होंगे।

{{sender_name}}

---
NyayCheck द्वारा जनरेट टेम्पलेट। भेजने से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "rti-application",
    title: { en: "RTI Application", hi: "RTI आवेदन" },
    description: { en: "Right to Information application template for ₹10.", hi: "₹10 के लिए सूचना का अधिकार आवेदन टेम्पलेट।" },
    category: "legal",
    fields: [
      { id: "applicant_name", label: { en: "Your Name", hi: "आपका नाम" }, type: "text", required: true },
      { id: "applicant_address", label: { en: "Your Address", hi: "आपका पता" }, type: "textarea", required: true },
      { id: "department", label: { en: "Department / Authority Name", hi: "विभाग / प्राधिकरण का नाम" }, type: "text", required: true },
      { id: "information_sought", label: { en: "Information you want", hi: "चाही गई जानकारी" }, type: "textarea", required: true },
      { id: "time_period", label: { en: "Time period (if applicable)", hi: "समय अवधि (यदि लागू)" }, type: "text", placeholder: "e.g. Jan 2023 - Dec 2024", required: false },
    ],
    template: {
      en: `APPLICATION UNDER THE RIGHT TO INFORMATION ACT, 2005

To,
The Public Information Officer (PIO)
{{department}}

From,
{{applicant_name}}
{{applicant_address}}

Date: {{today}}

Subject: Application under Section 6(1) of RTI Act, 2005

Sir/Madam,

I, {{applicant_name}}, wish to seek the following information under the Right to Information Act, 2005:

INFORMATION SOUGHT:
{{information_sought}}

TIME PERIOD: {{time_period}}

I am enclosing an application fee of ₹10 (Rupees Ten only) via [Court Fee Stamp / IPO / DD / Online Payment].

I request that the above information be provided within the stipulated 30 days as per the RTI Act.

If the information sought falls under the purview of another public authority, kindly transfer this application under Section 6(3) of the RTI Act.

Thanking you,

{{applicant_name}}

---
Template generated by NyayCheck. File online at rtionline.gov.in.`,
      hi: `सूचना का अधिकार अधिनियम, 2005 के तहत आवेदन

सेवा में,
जन सूचना अधिकारी (PIO)
{{department}}

प्रेषक,
{{applicant_name}}
{{applicant_address}}

दिनांक: {{today}}

विषय: RTI अधिनियम, 2005 की धारा 6(1) के तहत आवेदन

महोदय/महोदया,

मैं, {{applicant_name}}, सूचना का अधिकार अधिनियम, 2005 के तहत निम्नलिखित जानकारी प्राप्त करना चाहता/चाहती हूं:

चाही गई जानकारी:
{{information_sought}}

समय अवधि: {{time_period}}

मैं ₹10 का आवेदन शुल्क संलग्न कर रहा/रही हूं।

RTI अधिनियम के अनुसार 30 दिनों के भीतर उपरोक्त जानकारी प्रदान करने का अनुरोध है।

धन्यवाद,

{{applicant_name}}

---
NyayCheck द्वारा जनरेट टेम्पलेट। rtionline.gov.in पर ऑनलाइन दर्ज करें।`,
    },
  },
  {
    id: "salary-demand",
    title: { en: "Salary Demand Notice", hi: "वेतन मांग नोटिस" },
    description: { en: "Notice to employer for unpaid/withheld salary.", hi: "बकाया/रोके गए वेतन के लिए नियोक्ता को नोटिस।" },
    category: "employment",
    fields: [
      { id: "employee_name", label: { en: "Your Name", hi: "आपका नाम" }, type: "text", required: true },
      { id: "employee_address", label: { en: "Your Address", hi: "आपका पता" }, type: "textarea", required: true },
      { id: "company_name", label: { en: "Company Name", hi: "कंपनी का नाम" }, type: "text", required: true },
      { id: "company_address", label: { en: "Company Address", hi: "कंपनी का पता" }, type: "textarea", required: true },
      { id: "unpaid_months", label: { en: "Unpaid months", hi: "बकाया महीने" }, type: "text", placeholder: "e.g. Jan 2025 - Mar 2025", required: true },
      { id: "total_amount", label: { en: "Total amount due (₹)", hi: "कुल बकाया राशि (₹)" }, type: "number", required: true },
    ],
    template: {
      en: `LEGAL NOTICE FOR UNPAID SALARY

Date: {{today}}

To,
The Management
{{company_name}}
{{company_address}}

From,
{{employee_name}}
{{employee_address}}

Subject: Demand for payment of unpaid salary

Sir/Madam,

I, {{employee_name}}, was employed at {{company_name}}. My salary for the period {{unpaid_months}} amounting to ₹{{total_amount}} has not been paid despite repeated requests.

Non-payment of wages is a violation of the Payment of Wages Act, 1936 and constitutes an offence under Section 14 of the said Act.

You are hereby called upon to pay the outstanding amount of ₹{{total_amount}} within 15 days of receipt of this notice, failing which I shall be compelled to file a complaint with the Labour Commissioner and initiate legal proceedings.

{{employee_name}}

---
Template generated by NyayCheck. Consult a lawyer before sending.`,
      hi: `बकाया वेतन के लिए कानूनी नोटिस

दिनांक: {{today}}

सेवा में,
प्रबंधन
{{company_name}}
{{company_address}}

प्रेषक,
{{employee_name}}
{{employee_address}}

विषय: बकाया वेतन के भुगतान की मांग

महोदय/महोदया,

मैं, {{employee_name}}, {{company_name}} में कार्यरत था/थी। {{unpaid_months}} अवधि का मेरा वेतन ₹{{total_amount}} बार-बार अनुरोध के बावजूद नहीं दिया गया है।

वेतन का भुगतान न करना वेतन भुगतान अधिनियम, 1936 का उल्लंघन है।

इस नोटिस की प्राप्ति के 15 दिनों के भीतर ₹{{total_amount}} का भुगतान करें, अन्यथा मैं श्रम आयुक्त के पास शिकायत दर्ज करूंगा/करूंगी।

{{employee_name}}

---
NyayCheck द्वारा जनरेट टेम्पलेट। भेजने से पहले वकील से परामर्श करें।`,
    },
  },
];

export function getTemplateById(id: string): DocumentTemplate | undefined {
  return documentTemplates.find((t) => t.id === id);
}
