import type { BilingualText } from "@/types";

export interface TemplateField {
  id: string;
  label: BilingualText;
  type: "text" | "date" | "textarea" | "number";
  placeholder?: string;
  required: boolean;
}

export interface DocumentTemplate {
  id: string;
  title: BilingualText;
  description: BilingualText;
  category: string;
  fields: TemplateField[];
  template: BilingualText; // text with {{field_id}} placeholders
}

export const documentTemplates: DocumentTemplate[] = [
  {
    id: "rent-agreement",
    title: { en: "Rent Agreement (11 Months)", hi: "किराया अनुबंध (11 महीने)" },
    description: { en: "Standard residential rent agreement template.", hi: "मानक आवासीय किराया अनुबंध टेम्पलेट।" },
    category: "rent",
    fields: [
      { id: "landlord_name", label: { en: "Landlord Name", hi: "मकान मालिक का नाम" }, type: "text", required: true },
      { id: "tenant_name", label: { en: "Tenant Name", hi: "किरायेदार का नाम" }, type: "text", required: true },
      { id: "property_address", label: { en: "Property Address", hi: "संपत्ति का पता" }, type: "textarea", required: true },
      { id: "monthly_rent", label: { en: "Monthly Rent (₹)", hi: "मासिक किराया (₹)" }, type: "number", required: true },
      { id: "security_deposit", label: { en: "Security Deposit (₹)", hi: "सुरक्षा जमा (₹)" }, type: "number", required: true },
      { id: "start_date", label: { en: "Start Date", hi: "प्रारंभ तिथि" }, type: "date", required: true },
      { id: "notice_period", label: { en: "Notice Period (months)", hi: "नोटिस अवधि (महीने)" }, type: "number", placeholder: "1", required: true },
    ],
    template: {
      en: `RENT AGREEMENT

This Rent Agreement is made on {{start_date}} between:

LANDLORD: {{landlord_name}} (hereinafter referred to as "the Landlord")
TENANT: {{tenant_name}} (hereinafter referred to as "the Tenant")

For the property located at: {{property_address}}

TERMS AND CONDITIONS:

1. DURATION: This agreement is for a period of 11 (eleven) months commencing from {{start_date}}.

2. RENT: The Tenant shall pay a monthly rent of ₹{{monthly_rent}} (Rupees {{monthly_rent}} only), payable on or before the 5th of each month.

3. SECURITY DEPOSIT: The Tenant has paid a security deposit of ₹{{security_deposit}} (Rupees {{security_deposit}} only), refundable at the time of vacating, after deducting any damages.

4. NOTICE PERIOD: Either party must give {{notice_period}} month(s) written notice before vacating or terminating.

5. MAINTENANCE: Minor repairs up to ₹500 shall be borne by the Tenant. Major structural repairs by the Landlord.

6. USE: The premises shall be used for residential purposes only.

7. SUBLETTING: The Tenant shall not sublet the premises without written consent of the Landlord.

IN WITNESS WHEREOF, the parties have signed this agreement on the date mentioned above.


LANDLORD: ___________________     TENANT: ___________________
Name: {{landlord_name}}              Name: {{tenant_name}}

WITNESS 1: ___________________    WITNESS 2: ___________________

---
Template generated by NyayCheck. Please consult a lawyer before using.`,
      hi: `किराया अनुबंध

यह किराया अनुबंध {{start_date}} को निम्नलिखित पक्षों के बीच किया गया है:

मकान मालिक: {{landlord_name}} (इसके बाद "मकान मालिक" के रूप में संदर्भित)
किरायेदार: {{tenant_name}} (इसके बाद "किरायेदार" के रूप में संदर्भित)

संपत्ति का पता: {{property_address}}

नियम और शर्तें:

1. अवधि: यह अनुबंध {{start_date}} से 11 (ग्यारह) महीने की अवधि के लिए है।

2. किराया: किरायेदार प्रत्येक माह की 5 तारीख तक ₹{{monthly_rent}} मासिक किराया देगा।

3. सुरक्षा जमा: किरायेदार ने ₹{{security_deposit}} सुरक्षा जमा का भुगतान किया है, जो मकान खाली करते समय नुकसान की कटौती के बाद वापस किया जाएगा।

4. नोटिस अवधि: किसी भी पक्ष को खाली करने या समाप्त करने से {{notice_period}} महीने पहले लिखित नोटिस देना होगा।

5. रखरखाव: ₹500 तक की मामूली मरम्मत किरायेदार द्वारा। बड़ी संरचनात्मक मरम्मत मकान मालिक द्वारा।

6. उपयोग: परिसर केवल आवासीय उद्देश्य के लिए उपयोग किया जाएगा।


मकान मालिक: ___________________     किरायेदार: ___________________
नाम: {{landlord_name}}                   नाम: {{tenant_name}}

गवाह 1: ___________________          गवाह 2: ___________________

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "legal-notice",
    title: { en: "General Legal Notice", hi: "सामान्य कानूनी नोटिस" },
    description: { en: "Send a formal legal notice before taking legal action.", hi: "कानूनी कार्रवाई से पहले औपचारिक कानूनी नोटिस भेजें।" },
    category: "legal",
    fields: [
      { id: "sender_name", label: { en: "Your Name", hi: "आपका नाम" }, type: "text", required: true },
      { id: "sender_address", label: { en: "Your Address", hi: "आपका पता" }, type: "textarea", required: true },
      { id: "recipient_name", label: { en: "Recipient Name", hi: "प्राप्तकर्ता का नाम" }, type: "text", required: true },
      { id: "recipient_address", label: { en: "Recipient Address", hi: "प्राप्तकर्ता का पता" }, type: "textarea", required: true },
      { id: "subject", label: { en: "Subject", hi: "विषय" }, type: "text", required: true },
      { id: "facts", label: { en: "Facts of the matter", hi: "मामले के तथ्य" }, type: "textarea", required: true },
      { id: "demand", label: { en: "Your demand / relief sought", hi: "आपकी मांग / चाही गई राहत" }, type: "textarea", required: true },
      { id: "deadline_days", label: { en: "Response deadline (days)", hi: "जवाब की समय सीमा (दिन)" }, type: "number", placeholder: "15", required: true },
    ],
    template: {
      en: `LEGAL NOTICE

Date: {{today}}

To,
{{recipient_name}}
{{recipient_address}}

From,
{{sender_name}}
{{sender_address}}

Subject: {{subject}}

NOTICE

Under instructions from my client {{sender_name}}, I hereby serve upon you the following legal notice:

FACTS:
{{facts}}

DEMAND:
{{demand}}

You are hereby called upon to comply with the above demand within {{deadline_days}} days of receipt of this notice, failing which my client shall be constrained to initiate appropriate legal proceedings against you, at your risk, cost, and consequences.

This notice is sent without prejudice to any other rights and remedies available to my client under law.

{{sender_name}}

---
Template generated by NyayCheck. Consult a lawyer before sending.`,
      hi: `कानूनी नोटिस

दिनांक: {{today}}

सेवा में,
{{recipient_name}}
{{recipient_address}}

प्रेषक,
{{sender_name}}
{{sender_address}}

विषय: {{subject}}

नोटिस

अपने मुवक्किल {{sender_name}} के निर्देशानुसार, मैं आपको निम्नलिखित कानूनी नोटिस भेज रहा/रही हूं:

तथ्य:
{{facts}}

मांग:
{{demand}}

आपको इस नोटिस की प्राप्ति के {{deadline_days}} दिनों के भीतर उपरोक्त मांग का अनुपालन करने का आह्वान किया जाता है, अन्यथा मेरे मुवक्किल आपके जोखिम, लागत और परिणामों पर उचित कानूनी कार्यवाही शुरू करने के लिए बाध्य होंगे।

{{sender_name}}

---
NyayCheck द्वारा जनरेट टेम्पलेट। भेजने से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "rti-application",
    title: { en: "RTI Application", hi: "RTI आवेदन" },
    description: { en: "Right to Information application template for ₹10.", hi: "₹10 के लिए सूचना का अधिकार आवेदन टेम्पलेट।" },
    category: "legal",
    fields: [
      { id: "applicant_name", label: { en: "Your Name", hi: "आपका नाम" }, type: "text", required: true },
      { id: "applicant_address", label: { en: "Your Address", hi: "आपका पता" }, type: "textarea", required: true },
      { id: "department", label: { en: "Department / Authority Name", hi: "विभाग / प्राधिकरण का नाम" }, type: "text", required: true },
      { id: "information_sought", label: { en: "Information you want", hi: "चाही गई जानकारी" }, type: "textarea", required: true },
      { id: "time_period", label: { en: "Time period (if applicable)", hi: "समय अवधि (यदि लागू)" }, type: "text", placeholder: "e.g. Jan 2023 - Dec 2024", required: false },
    ],
    template: {
      en: `APPLICATION UNDER THE RIGHT TO INFORMATION ACT, 2005

To,
The Public Information Officer (PIO)
{{department}}

From,
{{applicant_name}}
{{applicant_address}}

Date: {{today}}

Subject: Application under Section 6(1) of RTI Act, 2005

Sir/Madam,

I, {{applicant_name}}, wish to seek the following information under the Right to Information Act, 2005:

INFORMATION SOUGHT:
{{information_sought}}

TIME PERIOD: {{time_period}}

I am enclosing an application fee of ₹10 (Rupees Ten only) via [Court Fee Stamp / IPO / DD / Online Payment].

I request that the above information be provided within the stipulated 30 days as per the RTI Act.

If the information sought falls under the purview of another public authority, kindly transfer this application under Section 6(3) of the RTI Act.

Thanking you,

{{applicant_name}}

---
Template generated by NyayCheck. File online at rtionline.gov.in.`,
      hi: `सूचना का अधिकार अधिनियम, 2005 के तहत आवेदन

सेवा में,
जन सूचना अधिकारी (PIO)
{{department}}

प्रेषक,
{{applicant_name}}
{{applicant_address}}

दिनांक: {{today}}

विषय: RTI अधिनियम, 2005 की धारा 6(1) के तहत आवेदन

महोदय/महोदया,

मैं, {{applicant_name}}, सूचना का अधिकार अधिनियम, 2005 के तहत निम्नलिखित जानकारी प्राप्त करना चाहता/चाहती हूं:

चाही गई जानकारी:
{{information_sought}}

समय अवधि: {{time_period}}

मैं ₹10 का आवेदन शुल्क संलग्न कर रहा/रही हूं।

RTI अधिनियम के अनुसार 30 दिनों के भीतर उपरोक्त जानकारी प्रदान करने का अनुरोध है।

धन्यवाद,

{{applicant_name}}

---
NyayCheck द्वारा जनरेट टेम्पलेट। rtionline.gov.in पर ऑनलाइन दर्ज करें।`,
    },
  },
  {
    id: "salary-demand",
    title: { en: "Salary Demand Notice", hi: "वेतन मांग नोटिस" },
    description: { en: "Notice to employer for unpaid/withheld salary.", hi: "बकाया/रोके गए वेतन के लिए नियोक्ता को नोटिस।" },
    category: "employment",
    fields: [
      { id: "employee_name", label: { en: "Your Name", hi: "आपका नाम" }, type: "text", required: true },
      { id: "employee_address", label: { en: "Your Address", hi: "आपका पता" }, type: "textarea", required: true },
      { id: "company_name", label: { en: "Company Name", hi: "कंपनी का नाम" }, type: "text", required: true },
      { id: "company_address", label: { en: "Company Address", hi: "कंपनी का पता" }, type: "textarea", required: true },
      { id: "unpaid_months", label: { en: "Unpaid months", hi: "बकाया महीने" }, type: "text", placeholder: "e.g. Jan 2025 - Mar 2025", required: true },
      { id: "total_amount", label: { en: "Total amount due (₹)", hi: "कुल बकाया राशि (₹)" }, type: "number", required: true },
    ],
    template: {
      en: `LEGAL NOTICE FOR UNPAID SALARY

Date: {{today}}

To,
The Management
{{company_name}}
{{company_address}}

From,
{{employee_name}}
{{employee_address}}

Subject: Demand for payment of unpaid salary

Sir/Madam,

I, {{employee_name}}, was employed at {{company_name}}. My salary for the period {{unpaid_months}} amounting to ₹{{total_amount}} has not been paid despite repeated requests.

Non-payment of wages is a violation of the Payment of Wages Act, 1936 and constitutes an offence under Section 14 of the said Act.

You are hereby called upon to pay the outstanding amount of ₹{{total_amount}} within 15 days of receipt of this notice, failing which I shall be compelled to file a complaint with the Labour Commissioner and initiate legal proceedings.

{{employee_name}}

---
Template generated by NyayCheck. Consult a lawyer before sending.`,
      hi: `बकाया वेतन के लिए कानूनी नोटिस

दिनांक: {{today}}

सेवा में,
प्रबंधन
{{company_name}}
{{company_address}}

प्रेषक,
{{employee_name}}
{{employee_address}}

विषय: बकाया वेतन के भुगतान की मांग

महोदय/महोदया,

मैं, {{employee_name}}, {{company_name}} में कार्यरत था/थी। {{unpaid_months}} अवधि का मेरा वेतन ₹{{total_amount}} बार-बार अनुरोध के बावजूद नहीं दिया गया है।

वेतन का भुगतान न करना वेतन भुगतान अधिनियम, 1936 का उल्लंघन है।

इस नोटिस की प्राप्ति के 15 दिनों के भीतर ₹{{total_amount}} का भुगतान करें, अन्यथा मैं श्रम आयुक्त के पास शिकायत दर्ज करूंगा/करूंगी।

{{employee_name}}

---
NyayCheck द्वारा जनरेट टेम्पलेट। भेजने से पहले वकील से परामर्श करें।`,
    },
  },

  // ========== NEW TEMPLATES ==========

  {
    id: "cheque-bounce-notice",
    title: { en: "Cheque Bounce Notice (S.138 NI Act)", hi: "चेक बाउंस नोटिस (धारा 138 NI अधिनियम)" },
    description: { en: "Legal notice for dishonoured cheque under Section 138 of the Negotiable Instruments Act, 1881.", hi: "परक्राम्य लिखत अधिनियम, 1881 की धारा 138 के तहत अनादरित चेक के लिए कानूनी नोटिस।" },
    category: "finance",
    fields: [
      { id: "sender", label: { en: "Your Name (Payee)", hi: "आपका नाम (प्राप्तकर्ता)" }, type: "text", required: true },
      { id: "recipient", label: { en: "Drawer Name", hi: "चेक जारीकर्ता का नाम" }, type: "text", required: true },
      { id: "cheque_number", label: { en: "Cheque Number", hi: "चेक संख्या" }, type: "text", required: true },
      { id: "cheque_date", label: { en: "Cheque Date", hi: "चेक की तारीख" }, type: "date", required: true },
      { id: "cheque_amount", label: { en: "Cheque Amount (₹)", hi: "चेक राशि (₹)" }, type: "number", required: true },
      { id: "bank_name", label: { en: "Drawee Bank Name", hi: "बैंक का नाम" }, type: "text", required: true },
      { id: "date_deposited", label: { en: "Date Deposited", hi: "जमा करने की तारीख" }, type: "date", required: true },
      { id: "date_returned", label: { en: "Date Returned Unpaid", hi: "अनादरित होने की तारीख" }, type: "date", required: true },
      { id: "return_reason", label: { en: "Reason for Return (as per memo)", hi: "वापसी का कारण (मेमो अनुसार)" }, type: "text", required: true },
    ],
    template: {
      en: `LEGAL NOTICE UNDER SECTION 138 OF THE NEGOTIABLE INSTRUMENTS ACT, 1881

Date: {{today}}

To,
{{recipient}}

From,
{{sender}}

Subject: Legal demand notice for dishonour of cheque no. {{cheque_number}}

NOTICE

Under instructions from {{sender}}, notice is hereby given to you as under:

1. You issued Cheque No. {{cheque_number}} dated {{cheque_date}} for an amount of ₹{{cheque_amount}} (Rupees {{cheque_amount}} only) drawn on {{bank_name}} in favour of {{sender}} towards discharge of a legally enforceable debt/liability.

2. The said cheque was presented for encashment on {{date_deposited}} but was returned dishonoured on {{date_returned}} with the remark: "{{return_reason}}".

3. The dishonour of the said cheque constitutes an offence punishable under Section 138 of the Negotiable Instruments Act, 1881.

DEMAND:

You are hereby called upon to make payment of the cheque amount of ₹{{cheque_amount}} within 15 (fifteen) days from the date of receipt of this notice, as mandated under the proviso to Section 138 of the NI Act.

In the event of your failure to make the said payment within the stipulated period of 15 days, my client shall be constrained to initiate criminal proceedings against you under Section 138 read with Section 142 of the Negotiable Instruments Act, 1881, at your risk, cost, and consequences. You shall also be liable for interest, costs, and compensation under Section 357 CrPC.

{{sender}}

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `परक्राम्य लिखत अधिनियम, 1881 की धारा 138 के तहत कानूनी नोटिस

दिनांक: {{today}}

सेवा में,
{{recipient}}

प्रेषक,
{{sender}}

विषय: चेक संख्या {{cheque_number}} के अनादरण हेतु कानूनी मांग नोटिस

नोटिस

{{sender}} के निर्देशानुसार, आपको निम्नानुसार नोटिस दिया जाता है:

1. आपने {{sender}} के पक्ष में कानूनी रूप से प्रवर्तनीय ऋण/देनदारी के निर्वहन हेतु {{bank_name}} पर आहरित ₹{{cheque_amount}} की राशि का चेक संख्या {{cheque_number}} दिनांक {{cheque_date}} जारी किया था।

2. उक्त चेक {{date_deposited}} को भुनाने हेतु प्रस्तुत किया गया, किन्तु {{date_returned}} को "{{return_reason}}" के कारण अनादरित लौटा दिया गया।

3. उक्त चेक का अनादरण परक्राम्य लिखत अधिनियम, 1881 की धारा 138 के तहत दण्डनीय अपराध है।

मांग:

आपको इस नोटिस की प्राप्ति की तारीख से 15 (पन्द्रह) दिनों के भीतर ₹{{cheque_amount}} की राशि का भुगतान करने का आह्वान किया जाता है, जैसा कि NI अधिनियम की धारा 138 के परन्तुक में अनिवार्य है।

निर्धारित 15 दिनों की अवधि में भुगतान करने में विफल रहने पर, मेरे मुवक्किल परक्राम्य लिखत अधिनियम, 1881 की धारा 138 सहपठित धारा 142 के तहत आपके विरुद्ध आपराधिक कार्यवाही प्रारम्भ करने को बाध्य होंगे।

{{sender}}

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "police-complaint-sp",
    title: { en: "Complaint to SP/DCP (Police Inaction)", hi: "SP/DCP को शिकायत (पुलिस निष्क्रियता)" },
    description: { en: "Written complaint to Superintendent of Police when police refuse to file FIR.", hi: "जब पुलिस FIR दर्ज करने से इनकार करे तो पुलिस अधीक्षक को लिखित शिकायत।" },
    category: "criminal",
    fields: [
      { id: "complainant_name", label: { en: "Your Name", hi: "आपका नाम" }, type: "text", required: true },
      { id: "complainant_address", label: { en: "Your Address", hi: "आपका पता" }, type: "textarea", required: true },
      { id: "complainant_phone", label: { en: "Your Phone Number", hi: "आपका फोन नम्बर" }, type: "text", required: true },
      { id: "sp_office", label: { en: "SP/DCP Office Name & District", hi: "SP/DCP कार्यालय का नाम एवं जिला" }, type: "text", required: true },
      { id: "police_station_name", label: { en: "Police Station Name", hi: "थाने का नाम" }, type: "text", required: true },
      { id: "date_of_incident", label: { en: "Date of Incident", hi: "घटना की तारीख" }, type: "date", required: true },
      { id: "incident_description", label: { en: "Describe the Incident", hi: "घटना का विवरण" }, type: "textarea", required: true },
      { id: "what_police_did", label: { en: "What did the police do/refuse?", hi: "पुलिस ने क्या किया/इनकार किया?" }, type: "textarea", required: true },
    ],
    template: {
      en: `WRITTEN COMPLAINT REGARDING POLICE INACTION

Date: {{today}}

To,
The Superintendent of Police / Deputy Commissioner of Police
{{sp_office}}

From,
{{complainant_name}}
{{complainant_address}}
Phone: {{complainant_phone}}

Subject: Complaint regarding failure of {{police_station_name}} to register FIR — violation of S.154 CrPC

Respected Sir/Madam,

I, {{complainant_name}}, respectfully submit this complaint regarding the failure of the police at {{police_station_name}} to register a First Information Report (FIR) in connection with a cognizable offence.

FACTS OF THE INCIDENT:

On {{date_of_incident}}, the following incident occurred:
{{incident_description}}

POLICE INACTION:

When I approached {{police_station_name}} to file an FIR, the following happened:
{{what_police_did}}

LEGAL PROVISIONS:

1. Under Section 154 of the Code of Criminal Procedure, 1973 (CrPC), the officer in charge of a police station is duty-bound to register an FIR upon receiving information of a cognizable offence. Refusal to register an FIR is itself an offence.

2. Under Section 166A of the Indian Penal Code (IPC), a public servant who knowingly disobeys the law regarding investigation is punishable with imprisonment up to two years and fine.

3. The Hon'ble Supreme Court in Lalita Kumari v. Govt. of U.P. (2014) held that registration of FIR is mandatory under Section 154 CrPC if the information discloses commission of a cognizable offence.

PRAYER:

I humbly request you to:
(a) Direct the SHO of {{police_station_name}} to register an FIR immediately.
(b) Take departmental action against the concerned officer for dereliction of duty.
(c) Ensure proper investigation of the case.

If no action is taken, I shall be constrained to approach the Hon'ble Magistrate under Section 156(3) CrPC.

Thanking you,

{{complainant_name}}

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `पुलिस निष्क्रियता के संबंध में लिखित शिकायत

दिनांक: {{today}}

सेवा में,
पुलिस अधीक्षक / पुलिस उपायुक्त
{{sp_office}}

प्रेषक,
{{complainant_name}}
{{complainant_address}}
फोन: {{complainant_phone}}

विषय: {{police_station_name}} द्वारा FIR दर्ज न करने संबंधी शिकायत — धारा 154 CrPC का उल्लंघन

माननीय महोदय/महोदया,

मैं, {{complainant_name}}, सविनय निवेदन करता/करती हूं कि {{police_station_name}} पुलिस ने संज्ञेय अपराध के संबंध में प्रथम सूचना रिपोर्ट (FIR) दर्ज करने से इनकार किया है।

घटना का विवरण:

दिनांक {{date_of_incident}} को निम्नलिखित घटना हुई:
{{incident_description}}

पुलिस की निष्क्रियता:

जब मैं {{police_station_name}} में FIR दर्ज कराने गया/गई, तो:
{{what_police_did}}

कानूनी प्रावधान:

1. दण्ड प्रक्रिया संहिता, 1973 (CrPC) की धारा 154 के तहत, थाना प्रभारी को संज्ञेय अपराध की सूचना मिलने पर FIR दर्ज करना अनिवार्य है। FIR दर्ज न करना स्वयं अपराध है।

2. भारतीय दण्ड संहिता (IPC) की धारा 166A के तहत, जो लोक सेवक जानबूझकर अन्वेषण संबंधी विधि का उल्लंघन करता है, उसे दो वर्ष तक के कारावास एवं जुर्माने से दण्डित किया जा सकता है।

3. माननीय सर्वोच्च न्यायालय ने ललिता कुमारी बनाम उत्तर प्रदेश सरकार (2014) में निर्णय दिया कि यदि सूचना से संज्ञेय अपराध का पता चलता है तो धारा 154 CrPC के तहत FIR दर्ज करना अनिवार्य है।

प्रार्थना:

मैं आपसे विनम्र अनुरोध करता/करती हूं:
(क) {{police_station_name}} के SHO को तुरन्त FIR दर्ज करने का निर्देश दें।
(ख) सम्बन्धित अधिकारी के विरुद्ध विभागीय कार्रवाई करें।
(ग) मामले की उचित जांच सुनिश्चित करें।

यदि कोई कार्रवाई नहीं होती, तो मैं धारा 156(3) CrPC के तहत माननीय मजिस्ट्रेट के समक्ष जाने को बाध्य हूं।

धन्यवाद,

{{complainant_name}}

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "magistrate-complaint-156",
    title: { en: "Complaint to Magistrate (S.156(3) CrPC)", hi: "मजिस्ट्रेट को शिकायत (धारा 156(3) CrPC)" },
    description: { en: "Application to Magistrate to direct police investigation when FIR is refused.", hi: "जब FIR से इनकार हो तो पुलिस जांच का निर्देश देने हेतु मजिस्ट्रेट को आवेदन।" },
    category: "criminal",
    fields: [
      { id: "complainant_name", label: { en: "Your Name", hi: "आपका नाम" }, type: "text", required: true },
      { id: "address", label: { en: "Your Address", hi: "आपका पता" }, type: "textarea", required: true },
      { id: "magistrate_court", label: { en: "Court of Magistrate (Name & District)", hi: "मजिस्ट्रेट न्यायालय (नाम एवं जिला)" }, type: "text", required: true },
      { id: "accused_name", label: { en: "Accused Name(s)", hi: "आरोपी का/के नाम" }, type: "text", required: true },
      { id: "accused_address", label: { en: "Accused Address", hi: "आरोपी का पता" }, type: "textarea", required: true },
      { id: "offence_description", label: { en: "Description of Offence", hi: "अपराध का विवरण" }, type: "textarea", required: true },
      { id: "police_station", label: { en: "Police Station Approached", hi: "जिस थाने में गए थे" }, type: "text", required: true },
      { id: "what_police_refused", label: { en: "How did the police refuse?", hi: "पुलिस ने कैसे इनकार किया?" }, type: "textarea", required: true },
    ],
    template: {
      en: `IN THE COURT OF {{magistrate_court}}

APPLICATION UNDER SECTION 156(3) OF THE CODE OF CRIMINAL PROCEDURE, 1973

Complainant: {{complainant_name}}, residing at {{address}}

Versus

Accused: {{accused_name}}, residing at {{accused_address}}

MOST RESPECTFULLY SHOWETH:

1. That the complainant is a law-abiding citizen and is filing this application under Section 156(3) read with Section 190 of the Code of Criminal Procedure, 1973 (CrPC).

2. That the following cognizable offence was committed by the accused:
{{offence_description}}

3. That the complainant approached {{police_station}} for registration of FIR, but the police refused/failed to take action as follows:
{{what_police_refused}}

4. That under Section 154 CrPC, it is mandatory for the police to register an FIR upon receiving information of a cognizable offence. The refusal of the police is illegal and in violation of law.

5. That under Section 156(3) CrPC, the Magistrate has the power to order the police to register an FIR and investigate the matter. The Hon'ble Supreme Court in Priyanka Srivastava v. State of U.P. (2015) has laid down guidelines for such applications.

6. That the complainant has no other efficacious remedy except to approach this Hon'ble Court.

PRAYER:

It is most respectfully prayed that this Hon'ble Court may be pleased to:

(a) Direct the SHO of {{police_station}} to register an FIR on the basis of the facts stated above;
(b) Direct the police to investigate the matter in accordance with law;
(c) Pass any other order that this Hon'ble Court deems fit and proper in the interest of justice.

COMPLAINANT

{{complainant_name}}
{{address}}

Date: {{today}}

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `न्यायालय {{magistrate_court}} में

दण्ड प्रक्रिया संहिता, 1973 की धारा 156(3) के तहत आवेदन

परिवादी: {{complainant_name}}, निवासी {{address}}

बनाम

आरोपी: {{accused_name}}, निवासी {{accused_address}}

सविनय निवेदन है कि:

1. परिवादी एक कानून का पालन करने वाला नागरिक है और यह आवेदन दण्ड प्रक्रिया संहिता, 1973 (CrPC) की धारा 156(3) सहपठित धारा 190 के तहत दाखिल कर रहा/रही है।

2. आरोपी द्वारा निम्नलिखित संज्ञेय अपराध किया गया:
{{offence_description}}

3. परिवादी ने {{police_station}} में FIR दर्ज कराने का प्रयास किया, किन्तु पुलिस ने निम्नानुसार कार्रवाई करने से इनकार किया:
{{what_police_refused}}

4. धारा 154 CrPC के तहत संज्ञेय अपराध की सूचना मिलने पर FIR दर्ज करना पुलिस का कर्तव्य है। पुलिस का इनकार अवैध एवं विधि विरुद्ध है।

5. धारा 156(3) CrPC के तहत मजिस्ट्रेट को पुलिस को FIR दर्ज करने एवं जांच करने का आदेश देने का अधिकार है। माननीय सर्वोच्च न्यायालय ने प्रियंका श्रीवास्तव बनाम उत्तर प्रदेश राज्य (2015) में ऐसे आवेदनों हेतु दिशा-निर्देश दिए हैं।

6. परिवादी के पास इस माननीय न्यायालय के समक्ष आने के अतिरिक्त कोई अन्य प्रभावी उपाय नहीं है।

प्रार्थना:

सविनय प्रार्थना है कि यह माननीय न्यायालय कृपया:

(क) {{police_station}} के SHO को उपरोक्त तथ्यों के आधार पर FIR दर्ज करने का निर्देश दें;
(ख) पुलिस को विधि अनुसार मामले की जांच करने का निर्देश दें;
(ग) न्याय हित में कोई अन्य उचित आदेश पारित करें।

परिवादी

{{complainant_name}}
{{address}}

दिनांक: {{today}}

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "consumer-complaint-edaakhil",
    title: { en: "Consumer Forum Complaint", hi: "उपभोक्ता फोरम शिकायत" },
    description: { en: "Consumer complaint format for filing at consumer forum / edaakhil.nic.in.", hi: "उपभोक्ता फोरम / edaakhil.nic.in पर दर्ज करने हेतु उपभोक्ता शिकायत प्रारूप।" },
    category: "consumer",
    fields: [
      { id: "complainant_name", label: { en: "Your Name", hi: "आपका नाम" }, type: "text", required: true },
      { id: "address", label: { en: "Your Address", hi: "आपका पता" }, type: "textarea", required: true },
      { id: "opposite_party_name", label: { en: "Opposite Party Name (Company/Seller)", hi: "विपक्षी का नाम (कम्पनी/विक्रेता)" }, type: "text", required: true },
      { id: "opposite_party_address", label: { en: "Opposite Party Address", hi: "विपक्षी का पता" }, type: "textarea", required: true },
      { id: "product_or_service", label: { en: "Product / Service", hi: "उत्पाद / सेवा" }, type: "text", required: true },
      { id: "purchase_date", label: { en: "Purchase / Availing Date", hi: "खरीद / लाभ लेने की तारीख" }, type: "date", required: true },
      { id: "amount", label: { en: "Amount Paid (₹)", hi: "भुगतान की गई राशि (₹)" }, type: "number", required: true },
      { id: "complaint_description", label: { en: "Describe your complaint in detail", hi: "अपनी शिकायत का विस्तार से वर्णन करें" }, type: "textarea", required: true },
      { id: "relief_sought", label: { en: "Relief / Compensation Sought", hi: "मांगी गई राहत / क्षतिपूर्ति" }, type: "textarea", required: true },
    ],
    template: {
      en: `BEFORE THE DISTRICT CONSUMER DISPUTES REDRESSAL COMMISSION

CONSUMER COMPLAINT UNDER SECTION 35 OF THE CONSUMER PROTECTION ACT, 2019

Complainant:
{{complainant_name}}
{{address}}

Versus

Opposite Party:
{{opposite_party_name}}
{{opposite_party_address}}

FACTS OF THE COMPLAINT:

1. The complainant is a "consumer" as defined under Section 2(7) of the Consumer Protection Act, 2019, having purchased/availed the following product/service:

   Product/Service: {{product_or_service}}
   Date of Purchase: {{purchase_date}}
   Amount Paid: ₹{{amount}}

2. The complainant states that:
{{complaint_description}}

3. The acts of the Opposite Party constitute "deficiency in service" and/or "defect in goods" as defined under the Consumer Protection Act, 2019.

4. The complainant has suffered loss and injury due to the unfair trade practice / deficiency in service / defective goods of the Opposite Party.

RELIEF SOUGHT:

The complainant prays for the following relief:
{{relief_sought}}

Along with:
(a) Compensation for mental agony and harassment
(b) Cost of litigation
(c) Any other relief deemed fit by this Hon'ble Commission

VERIFICATION:

I, {{complainant_name}}, do hereby verify that the contents of this complaint are true and correct to the best of my knowledge and belief.

{{complainant_name}}
Date: {{today}}
Place: ___________________

Note: This complaint may be filed online at https://edaakhil.nic.in

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `जिला उपभोक्ता विवाद निवारण आयोग के समक्ष

उपभोक्ता संरक्षण अधिनियम, 2019 की धारा 35 के तहत उपभोक्ता शिकायत

परिवादी:
{{complainant_name}}
{{address}}

बनाम

विपक्षी:
{{opposite_party_name}}
{{opposite_party_address}}

शिकायत के तथ्य:

1. परिवादी उपभोक्ता संरक्षण अधिनियम, 2019 की धारा 2(7) के तहत परिभाषित "उपभोक्ता" है, जिसने निम्नलिखित उत्पाद/सेवा खरीदी/प्राप्त की:

   उत्पाद/सेवा: {{product_or_service}}
   खरीद की तारीख: {{purchase_date}}
   भुगतान की गई राशि: ₹{{amount}}

2. परिवादी का कथन है कि:
{{complaint_description}}

3. विपक्षी के कृत्य उपभोक्ता संरक्षण अधिनियम, 2019 के तहत "सेवा में कमी" और/या "माल में दोष" की श्रेणी में आते हैं।

4. विपक्षी की अनुचित व्यापार प्रथा / सेवा में कमी / दोषपूर्ण माल के कारण परिवादी को हानि एवं क्षति हुई है।

मांगी गई राहत:

परिवादी निम्नलिखित राहत की प्रार्थना करता/करती है:
{{relief_sought}}

साथ ही:
(क) मानसिक पीड़ा एवं उत्पीड़न हेतु क्षतिपूर्ति
(ख) वाद व्यय
(ग) कोई अन्य राहत जो यह माननीय आयोग उचित समझे

सत्यापन:

मैं, {{complainant_name}}, सत्यापित करता/करती हूं कि इस शिकायत की विषय-वस्तु मेरी जानकारी एवं विश्वास के अनुसार सत्य एवं सही है।

{{complainant_name}}
दिनांक: {{today}}
स्थान: ___________________

नोट: यह शिकायत https://edaakhil.nic.in पर ऑनलाइन दर्ज की जा सकती है

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "general-affidavit",
    title: { en: "General Affidavit", hi: "सामान्य शपथ पत्र" },
    description: { en: "Universal affidavit format for any legal purpose.", hi: "किसी भी कानूनी उद्देश्य हेतु सामान्य शपथ पत्र प्रारूप।" },
    category: "legal",
    fields: [
      { id: "deponent_name", label: { en: "Your Name (Deponent)", hi: "आपका नाम (शपथकर्ता)" }, type: "text", required: true },
      { id: "deponent_address", label: { en: "Your Address", hi: "आपका पता" }, type: "textarea", required: true },
      { id: "deponent_age", label: { en: "Your Age", hi: "आपकी आयु" }, type: "number", required: true },
      { id: "father_name", label: { en: "Father's / Husband's Name", hi: "पिता / पति का नाम" }, type: "text", required: true },
      { id: "purpose", label: { en: "Purpose of Affidavit", hi: "शपथ पत्र का उद्देश्य" }, type: "text", required: true },
      { id: "statement_content", label: { en: "Content of Statement / Declaration", hi: "कथन / घोषणा की विषय-वस्तु" }, type: "textarea", required: true },
    ],
    template: {
      en: `AFFIDAVIT

(On Stamp Paper of appropriate value)

I, {{deponent_name}}, aged {{deponent_age}} years, son/daughter/wife of {{father_name}}, residing at {{deponent_address}}, do hereby solemnly affirm and declare as under:

PURPOSE: {{purpose}}

STATEMENT:

1. That I am the deponent herein and am competent to swear this affidavit.

2. That I state on solemn affirmation as follows:

{{statement_content}}

3. That the contents of this affidavit are true and correct to the best of my knowledge and belief, and nothing material has been concealed therefrom.

VERIFICATION

I, {{deponent_name}}, the above-named deponent, do hereby verify that the contents of the above affidavit are true and correct to the best of my knowledge and belief and no part of it is false and nothing material has been concealed therefrom.

Verified at ___________________ on {{today}}.

DEPONENT

{{deponent_name}}

(Signature / Thumb Impression)

BEFORE ME

Notary Public / Oath Commissioner

Seal & Signature: ___________________

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `शपथ पत्र

(उचित मूल्य के स्टाम्प पेपर पर)

मैं, {{deponent_name}}, आयु {{deponent_age}} वर्ष, पुत्र/पुत्री/पत्नी {{father_name}}, निवासी {{deponent_address}}, सशपथ कथन करता/करती हूं कि:

उद्देश्य: {{purpose}}

कथन:

1. मैं इस शपथ पत्र का शपथकर्ता हूं और यह शपथ पत्र देने में सक्षम हूं।

2. मैं सत्यनिष्ठा से निम्नानुसार कथन करता/करती हूं:

{{statement_content}}

3. इस शपथ पत्र की विषय-वस्तु मेरी जानकारी एवं विश्वास के अनुसार सत्य एवं सही है, तथा इसमें कोई भी महत्वपूर्ण तथ्य छुपाया नहीं गया है।

सत्यापन

मैं, {{deponent_name}}, उपर्युक्त शपथकर्ता, सत्यापित करता/करती हूं कि उपरोक्त शपथ पत्र की विषय-वस्तु मेरी जानकारी एवं विश्वास के अनुसार सत्य एवं सही है तथा इसका कोई भी भाग असत्य नहीं है।

स्थान ___________________ दिनांक {{today}} को सत्यापित।

शपथकर्ता

{{deponent_name}}

(हस्ताक्षर / अंगूठे का निशान)

मेरे समक्ष

नोटरी पब्लिक / शपथ आयुक्त

मुहर एवं हस्ताक्षर: ___________________

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "power-of-attorney",
    title: { en: "General Power of Attorney", hi: "सामान्य मुख्तारनामा" },
    description: { en: "General Power of Attorney to authorize someone to act on your behalf.", hi: "किसी को आपकी ओर से कार्य करने हेतु अधिकृत करने का सामान्य मुख्तारनामा।" },
    category: "property",
    fields: [
      { id: "principal_name", label: { en: "Principal Name (You)", hi: "मुख्य व्यक्ति का नाम (आप)" }, type: "text", required: true },
      { id: "principal_address", label: { en: "Principal Address", hi: "मुख्य व्यक्ति का पता" }, type: "textarea", required: true },
      { id: "agent_name", label: { en: "Agent / Attorney Name", hi: "एजेंट / मुख्तार का नाम" }, type: "text", required: true },
      { id: "agent_address", label: { en: "Agent Address", hi: "एजेंट का पता" }, type: "textarea", required: true },
      { id: "powers_granted", label: { en: "Powers Granted (describe in detail)", hi: "दिए जा रहे अधिकार (विस्तार से लिखें)" }, type: "textarea", required: true },
      { id: "duration", label: { en: "Duration / Validity Period", hi: "अवधि / वैधता अवधि" }, type: "text", required: true },
    ],
    template: {
      en: `GENERAL POWER OF ATTORNEY

(To be executed on non-judicial stamp paper of appropriate value as per state rules under the Powers of Attorney Act, 1882)

KNOW ALL MEN BY THESE PRESENTS:

I, {{principal_name}}, residing at {{principal_address}}, hereinafter referred to as the "Principal/Executant", do hereby appoint, nominate, constitute, and authorize:

{{agent_name}}, residing at {{agent_address}}, hereinafter referred to as my "Attorney/Agent",

to act, do, and execute all or any of the following acts, deeds, and things on my behalf:

POWERS GRANTED:

{{powers_granted}}

GENERAL CLAUSES:

1. The Attorney shall have the power to do all acts, deeds, and things as may be necessary and incidental to the exercise of the above powers.

2. The Attorney may sign, execute, and deliver all documents, applications, and papers as may be required.

3. All acts done by the said Attorney under this Power of Attorney shall be binding upon me as if done by me personally.

4. This Power of Attorney shall remain valid for: {{duration}}

5. This Power of Attorney is irrevocable during the said period unless revoked by a written instrument duly executed and registered.

6. This Power of Attorney is executed under the Powers of Attorney Act, 1882.

IN WITNESS WHEREOF, I have executed this Power of Attorney on {{today}}.

PRINCIPAL / EXECUTANT

{{principal_name}}

(Signature)

ACCEPTED BY ATTORNEY:

{{agent_name}}

(Signature)

WITNESS 1: ___________________    WITNESS 2: ___________________

Note: Must be executed on stamp paper of requisite value and registered with the Sub-Registrar's Office.

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `सामान्य मुख्तारनामा (पावर ऑफ अटॉर्नी)

(मुख्तारनामा अधिनियम, 1882 के तहत राज्य के नियमों के अनुसार उचित मूल्य के गैर-न्यायिक स्टाम्प पेपर पर निष्पादित किया जाए)

सर्वविदित हो कि:

मैं, {{principal_name}}, निवासी {{principal_address}}, जिसे इसके बाद "मुख्य व्यक्ति/निष्पादक" कहा जाएगा, एतद्द्वारा:

{{agent_name}}, निवासी {{agent_address}}, जिसे इसके बाद मेरा "मुख्तार/एजेंट" कहा जाएगा,

को मेरी ओर से निम्नलिखित सभी या कोई भी कार्य, कर्म एवं विषय करने, निष्पादित करने हेतु नियुक्त, नामित, गठित एवं अधिकृत करता/करती हूं:

दिए जा रहे अधिकार:

{{powers_granted}}

सामान्य खण्ड:

1. मुख्तार को उपरोक्त अधिकारों के प्रयोग हेतु सभी आवश्यक एवं आनुषंगिक कार्य करने का अधिकार होगा।

2. मुख्तार सभी आवश्यक दस्तावेजों, आवेदनों एवं कागजातों पर हस्ताक्षर, निष्पादन एवं वितरण कर सकता/सकती है।

3. इस मुख्तारनामे के तहत मुख्तार द्वारा किए गए सभी कार्य मुझ पर बाध्यकारी होंगे।

4. यह मुख्तारनामा इस अवधि तक वैध रहेगा: {{duration}}

5. यह मुख्तारनामा मुख्तारनामा अधिनियम, 1882 के तहत निष्पादित है।

मैंने यह मुख्तारनामा {{today}} को निष्पादित किया है।

मुख्य व्यक्ति / निष्पादक

{{principal_name}}

(हस्ताक्षर)

मुख्तार द्वारा स्वीकृत:

{{agent_name}}

(हस्ताक्षर)

गवाह 1: ___________________    गवाह 2: ___________________

नोट: इसे आवश्यक मूल्य के स्टाम्प पेपर पर निष्पादित कर उप-पंजीयक कार्यालय में पंजीकृत कराना अनिवार्य है।

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "will-testament",
    title: { en: "Last Will and Testament", hi: "अंतिम वसीयतनामा" },
    description: { en: "Template for making a Last Will and Testament.", hi: "अंतिम वसीयतनामा बनाने हेतु टेम्पलेट।" },
    category: "family",
    fields: [
      { id: "testator_name", label: { en: "Your Name (Testator)", hi: "आपका नाम (वसीयतकर्ता)" }, type: "text", required: true },
      { id: "testator_address", label: { en: "Your Address", hi: "आपका पता" }, type: "textarea", required: true },
      { id: "testator_age", label: { en: "Your Age", hi: "आपकी आयु" }, type: "number", required: true },
      { id: "beneficiary_1_name", label: { en: "Beneficiary 1 Name", hi: "लाभार्थी 1 का नाम" }, type: "text", required: true },
      { id: "beneficiary_1_relation", label: { en: "Beneficiary 1 Relation", hi: "लाभार्थी 1 का सम्बन्ध" }, type: "text", required: true },
      { id: "beneficiary_1_share", label: { en: "Beneficiary 1 Share / Bequest", hi: "लाभार्थी 1 का हिस्सा / वसीयत" }, type: "textarea", required: true },
      { id: "beneficiary_2_name", label: { en: "Beneficiary 2 Name", hi: "लाभार्थी 2 का नाम" }, type: "text", required: true },
      { id: "beneficiary_2_relation", label: { en: "Beneficiary 2 Relation", hi: "लाभार्थी 2 का सम्बन्ध" }, type: "text", required: true },
      { id: "beneficiary_2_share", label: { en: "Beneficiary 2 Share / Bequest", hi: "लाभार्थी 2 का हिस्सा / वसीयत" }, type: "textarea", required: true },
      { id: "executor_name", label: { en: "Executor Name", hi: "निष्पादक का नाम" }, type: "text", required: true },
      { id: "executor_address", label: { en: "Executor Address", hi: "निष्पादक का पता" }, type: "textarea", required: true },
    ],
    template: {
      en: `LAST WILL AND TESTAMENT

I, {{testator_name}}, aged {{testator_age}} years, residing at {{testator_address}}, being of sound mind and disposing memory, do hereby declare this to be my Last Will and Testament.

REVOCATION CLAUSE:
I hereby revoke all former Wills, Codicils, and Testamentary dispositions made by me at any time heretofore.

DECLARATIONS:
1. I am making this Will of my own free will and volition without any coercion, undue influence, or pressure from any person.
2. I am in sound mental and physical health at the time of execution of this Will.

BEQUESTS:

1. I bequeath to {{beneficiary_1_name}} (my {{beneficiary_1_relation}}):
{{beneficiary_1_share}}

2. I bequeath to {{beneficiary_2_name}} (my {{beneficiary_2_relation}}):
{{beneficiary_2_share}}

EXECUTOR:
I appoint {{executor_name}}, residing at {{executor_address}}, as the Executor of this Will, who shall be responsible for carrying out the provisions of this Will.

GENERAL:
1. In case any beneficiary predeceases me, their share shall devolve upon their legal heirs.
2. The Executor shall have the power to sell, transfer, or deal with the properties as may be necessary for the administration of this Will.

IN WITNESS WHEREOF, I have signed this Will on {{today}} in the presence of the following witnesses, who have also signed in my presence and in the presence of each other.

TESTATOR:

{{testator_name}}
(Signature)

WITNESS 1:
Name: ___________________
Address: ___________________
Signature: ___________________

WITNESS 2:
Name: ___________________
Address: ___________________
Signature: ___________________

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `अंतिम वसीयतनामा

मैं, {{testator_name}}, आयु {{testator_age}} वर्ष, निवासी {{testator_address}}, स्वस्थ मस्तिष्क एवं स्मरण शक्ति से युक्त होकर, एतद्द्वारा इसे अपना अंतिम वसीयतनामा घोषित करता/करती हूं।

निरसन खण्ड:
मैं एतद्द्वारा अपनी पूर्व में किसी भी समय बनाई गई सभी वसीयतों, परिशिष्टों एवं वसीयती व्ययनों को निरस्त करता/करती हूं।

घोषणाएं:
1. मैं यह वसीयत अपनी स्वतंत्र इच्छा से किसी भी व्यक्ति के दबाव, अनुचित प्रभाव या बल के बिना बना रहा/रही हूं।
2. इस वसीयत के निष्पादन के समय मेरा मानसिक एवं शारीरिक स्वास्थ्य ठीक है।

वसीयत:

1. मैं {{beneficiary_1_name}} (मेरे/मेरी {{beneficiary_1_relation}}) को निम्नलिखित वसीयत करता/करती हूं:
{{beneficiary_1_share}}

2. मैं {{beneficiary_2_name}} (मेरे/मेरी {{beneficiary_2_relation}}) को निम्नलिखित वसीयत करता/करती हूं:
{{beneficiary_2_share}}

निष्पादक:
मैं {{executor_name}}, निवासी {{executor_address}} को इस वसीयत का निष्पादक नियुक्त करता/करती हूं, जो इस वसीयत के प्रावधानों को कार्यान्वित करने के लिए उत्तरदायी होगा/होगी।

सामान्य:
1. यदि कोई लाभार्थी मुझसे पहले मृत्यु को प्राप्त होता है, तो उसका हिस्सा उसके कानूनी उत्तराधिकारियों को प्राप्त होगा।
2. निष्पादक को इस वसीयत के प्रशासन हेतु सम्पत्तियों को बेचने, हस्तांतरित करने या व्यवहार करने का अधिकार होगा।

मैंने {{today}} को निम्नलिखित गवाहों की उपस्थिति में इस वसीयत पर हस्ताक्षर किए हैं, जिन्होंने भी मेरी एवं एक दूसरे की उपस्थिति में हस्ताक्षर किए हैं।

वसीयतकर्ता:

{{testator_name}}
(हस्ताक्षर)

गवाह 1:
नाम: ___________________
पता: ___________________
हस्ताक्षर: ___________________

गवाह 2:
नाम: ___________________
पता: ___________________
हस्ताक्षर: ___________________

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "domestic-violence-complaint",
    title: { en: "Domestic Violence Complaint (DV Act 2005)", hi: "घरेलू हिंसा शिकायत (DV अधिनियम 2005)" },
    description: { en: "Complaint under the Protection of Women from Domestic Violence Act, 2005.", hi: "घरेलू हिंसा से महिलाओं के संरक्षण अधिनियम, 2005 के तहत शिकायत।" },
    category: "family",
    fields: [
      { id: "complainant_name", label: { en: "Your Name (Aggrieved Person)", hi: "आपका नाम (पीड़ित व्यक्ति)" }, type: "text", required: true },
      { id: "complainant_address", label: { en: "Your Address", hi: "आपका पता" }, type: "textarea", required: true },
      { id: "respondent_name", label: { en: "Respondent Name", hi: "प्रतिवादी का नाम" }, type: "text", required: true },
      { id: "respondent_relation", label: { en: "Relation with Respondent", hi: "प्रतिवादी से सम्बन्ध" }, type: "text", required: true },
      { id: "respondent_address", label: { en: "Respondent Address", hi: "प्रतिवादी का पता" }, type: "textarea", required: true },
      { id: "type_of_violence", label: { en: "Type & Details of Violence", hi: "हिंसा का प्रकार एवं विवरण" }, type: "textarea", required: true },
      { id: "since_when", label: { en: "Since when has this been happening?", hi: "यह कब से हो रहा है?" }, type: "text", required: true },
      { id: "relief_sought", label: { en: "Relief Sought", hi: "मांगी गई राहत" }, type: "textarea", required: true },
    ],
    template: {
      en: `APPLICATION UNDER THE PROTECTION OF WOMEN FROM DOMESTIC VIOLENCE ACT, 2005

To,
The Protection Officer / Magistrate
___________________

From,
{{complainant_name}} (Aggrieved Person)
{{complainant_address}}

Date: {{today}}

Subject: Complaint under the Protection of Women from Domestic Violence Act, 2005

Respondent:
{{respondent_name}} ({{respondent_relation}})
{{respondent_address}}

COMPLAINT:

I, {{complainant_name}}, the aggrieved person, hereby submit this complaint under the Protection of Women from Domestic Violence Act, 2005 (DV Act) against the respondent {{respondent_name}}, who is my {{respondent_relation}}.

DETAILS OF DOMESTIC VIOLENCE:

The respondent has been subjecting me to domestic violence as defined under Section 3 of the DV Act, 2005, which includes physical abuse, sexual abuse, verbal and emotional abuse, and economic abuse. The details are as follows:

{{type_of_violence}}

This has been occurring since: {{since_when}}

RELIEF SOUGHT UNDER THE DV ACT:

I pray for the following relief:

{{relief_sought}}

Specifically, I seek:
(a) Protection Order under Section 18 of the DV Act — restraining the respondent from committing any act of domestic violence
(b) Residence Order under Section 19 of the DV Act — securing my right to reside in the shared household
(c) Monetary Relief under Section 20 of the DV Act
(d) Compensation Order under Section 22 of the DV Act
(e) Any other relief this Hon'ble Court deems fit

I state that the above facts are true to the best of my knowledge and belief.

{{complainant_name}}
(Signature)

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `घरेलू हिंसा से महिलाओं के संरक्षण अधिनियम, 2005 के तहत आवेदन

सेवा में,
संरक्षण अधिकारी / मजिस्ट्रेट
___________________

प्रेषक,
{{complainant_name}} (पीड़ित व्यक्ति)
{{complainant_address}}

दिनांक: {{today}}

विषय: घरेलू हिंसा से महिलाओं के संरक्षण अधिनियम, 2005 के तहत शिकायत

प्रतिवादी:
{{respondent_name}} ({{respondent_relation}})
{{respondent_address}}

शिकायत:

मैं, {{complainant_name}}, पीड़ित व्यक्ति, एतद्द्वारा प्रतिवादी {{respondent_name}} जो मेरे/मेरी {{respondent_relation}} हैं, के विरुद्ध घरेलू हिंसा से महिलाओं के संरक्षण अधिनियम, 2005 (DV अधिनियम) के तहत यह शिकायत प्रस्तुत करती हूं।

घरेलू हिंसा का विवरण:

प्रतिवादी मुझे DV अधिनियम, 2005 की धारा 3 में परिभाषित घरेलू हिंसा — जिसमें शारीरिक, यौन, मौखिक व भावनात्मक तथा आर्थिक शोषण सम्मिलित है — का शिकार बना रहा/रही है। विवरण इस प्रकार है:

{{type_of_violence}}

यह कब से हो रहा है: {{since_when}}

DV अधिनियम के तहत मांगी गई राहत:

मैं निम्नलिखित राहत की प्रार्थना करती हूं:

{{relief_sought}}

विशेष रूप से, मैं मांग करती हूं:
(क) DV अधिनियम की धारा 18 के तहत संरक्षण आदेश — प्रतिवादी को घरेलू हिंसा का कोई भी कार्य करने से रोकना
(ख) DV अधिनियम की धारा 19 के तहत निवास आदेश — साझा गृहस्थी में मेरे निवास के अधिकार को सुरक्षित करना
(ग) DV अधिनियम की धारा 20 के तहत आर्थिक राहत
(घ) DV अधिनियम की धारा 22 के तहत क्षतिपूर्ति आदेश
(ङ) कोई अन्य राहत जो यह माननीय न्यायालय उचित समझे

मैं कथन करती हूं कि उपरोक्त तथ्य मेरी जानकारी एवं विश्वास के अनुसार सत्य हैं।

{{complainant_name}}
(हस्ताक्षर)

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "eviction-response",
    title: { en: "Reply to Illegal Eviction Notice", hi: "अवैध बेदखली नोटिस का उत्तर" },
    description: { en: "Tenant's reply to an illegal or wrongful eviction notice from landlord.", hi: "मकान मालिक के अवैध बेदखली नोटिस का किरायेदार का उत्तर।" },
    category: "rent",
    fields: [
      { id: "tenant_name", label: { en: "Your Name (Tenant)", hi: "आपका नाम (किरायेदार)" }, type: "text", required: true },
      { id: "tenant_address", label: { en: "Your Address (Rented Premises)", hi: "आपका पता (किराये का परिसर)" }, type: "textarea", required: true },
      { id: "landlord_name", label: { en: "Landlord Name", hi: "मकान मालिक का नाम" }, type: "text", required: true },
      { id: "landlord_address", label: { en: "Landlord Address", hi: "मकान मालिक का पता" }, type: "textarea", required: true },
      { id: "eviction_notice_date", label: { en: "Date of Eviction Notice Received", hi: "बेदखली नोटिस प्राप्ति की तारीख" }, type: "date", required: true },
      { id: "rent_agreement_date", label: { en: "Date of Rent Agreement", hi: "किराया अनुबंध की तारीख" }, type: "date", required: true },
      { id: "reasons_against_eviction", label: { en: "Reasons why eviction is illegal/wrong", hi: "बेदखली अवैध/गलत क्यों है, इसके कारण" }, type: "textarea", required: true },
    ],
    template: {
      en: `REPLY TO EVICTION NOTICE

Date: {{today}}

To,
{{landlord_name}}
{{landlord_address}}

From,
{{tenant_name}}
{{tenant_address}}

Subject: Reply to your eviction notice dated {{eviction_notice_date}}

Sir/Madam,

I, {{tenant_name}}, am in receipt of your purported eviction notice dated {{eviction_notice_date}}.

I am a lawful tenant of the premises at {{tenant_address}} under a valid rent agreement dated {{rent_agreement_date}}. I hereby deny and dispute the contents of your said notice and state as follows:

GROUNDS AGAINST EVICTION:

{{reasons_against_eviction}}

LEGAL POSITION:

1. Under the applicable State Rent Control Act, a landlord cannot evict a tenant except on grounds specified in the statute and only through due process of law, i.e., by filing a suit/petition before the Rent Controller/competent court.

2. Self-help eviction, disconnection of essential services (water, electricity), or use of force to dispossess a tenant is illegal and actionable.

3. Any eviction without following due process shall be treated as illegal dispossession, and I reserve my right to seek protection from the competent court including damages and injunction.

4. I am a regular tenant who has been paying rent and fulfilling all obligations under the rent agreement.

NOTICE:

You are hereby put on notice that:
(a) Your purported eviction notice is illegal, arbitrary, and without basis in law.
(b) Any attempt to forcefully evict me or disconnect essential services shall invite legal consequences.
(c) I reserve my right to approach the Rent Controller / competent court for appropriate relief.

{{tenant_name}}

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `बेदखली नोटिस का उत्तर

दिनांक: {{today}}

सेवा में,
{{landlord_name}}
{{landlord_address}}

प्रेषक,
{{tenant_name}}
{{tenant_address}}

विषय: आपके दिनांक {{eviction_notice_date}} के बेदखली नोटिस का उत्तर

महोदय/महोदया,

मैं, {{tenant_name}}, को आपका कथित बेदखली नोटिस दिनांक {{eviction_notice_date}} प्राप्त हुआ है।

मैं {{tenant_address}} परिसर का वैध किरायेदार हूं जो दिनांक {{rent_agreement_date}} के वैध किराया अनुबंध के तहत है। मैं आपके उक्त नोटिस की विषय-वस्तु को अस्वीकार एवं विवादित करता/करती हूं तथा निम्नानुसार कथन करता/करती हूं:

बेदखली के विरुद्ध आधार:

{{reasons_against_eviction}}

कानूनी स्थिति:

1. लागू राज्य किराया नियंत्रण अधिनियम के तहत, मकान मालिक किरायेदार को केवल अधिनियम में निर्दिष्ट आधारों पर और केवल विधि द्वारा स्थापित प्रक्रिया — अर्थात किराया नियंत्रक/सक्षम न्यायालय के समक्ष वाद/याचिका दायर करके — ही बेदखल कर सकता है।

2. स्वयं बलपूर्वक बेदखली, आवश्यक सेवाओं (पानी, बिजली) का विच्छेद, या किरायेदार को बलपूर्वक बेदखल करना अवैध एवं कार्रवाई योग्य है।

3. उचित प्रक्रिया का पालन किए बिना कोई भी बेदखली अवैध विस्थापन मानी जाएगी, और मैं सक्षम न्यायालय से क्षतिपूर्ति एवं निषेधाज्ञा सहित संरक्षण मांगने का अधिकार सुरक्षित रखता/रखती हूं।

4. मैं एक नियमित किरायेदार हूं जो किराया चुकाता/चुकाती रहा/रही हूं और किराया अनुबंध के सभी दायित्वों का पालन करता/करती रहा/रही हूं।

सूचना:

आपको एतद्द्वारा सूचित किया जाता है कि:
(क) आपका कथित बेदखली नोटिस अवैध, मनमाना एवं विधि में आधारहीन है।
(ख) मुझे बलपूर्वक बेदखल करने या आवश्यक सेवाएं काटने का कोई भी प्रयास कानूनी परिणाम आमंत्रित करेगा।
(ग) मैं उचित राहत हेतु किराया नियंत्रक / सक्षम न्यायालय में जाने का अधिकार सुरक्षित रखता/रखती हूं।

{{tenant_name}}

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "experience-letter-demand",
    title: { en: "Demand for Experience / Relieving Letter", hi: "अनुभव / कार्यमुक्ति पत्र की मांग" },
    description: { en: "Demand notice to employer for issuing experience or relieving letter.", hi: "अनुभव या कार्यमुक्ति पत्र जारी करने हेतु नियोक्ता को मांग नोटिस।" },
    category: "employment",
    fields: [
      { id: "employee_name", label: { en: "Your Name", hi: "आपका नाम" }, type: "text", required: true },
      { id: "employee_address", label: { en: "Your Address", hi: "आपका पता" }, type: "textarea", required: true },
      { id: "company_name", label: { en: "Company Name", hi: "कम्पनी का नाम" }, type: "text", required: true },
      { id: "company_address", label: { en: "Company Address", hi: "कम्पनी का पता" }, type: "textarea", required: true },
      { id: "designation", label: { en: "Your Designation", hi: "आपका पदनाम" }, type: "text", required: true },
      { id: "joining_date", label: { en: "Joining Date", hi: "कार्यग्रहण तिथि" }, type: "date", required: true },
      { id: "last_working_date", label: { en: "Last Working Date", hi: "अंतिम कार्य दिवस" }, type: "date", required: true },
      { id: "reason_for_demand", label: { en: "Why you need it / What happened", hi: "आपको इसकी आवश्यकता क्यों है / क्या हुआ" }, type: "textarea", required: true },
    ],
    template: {
      en: `DEMAND NOTICE FOR EXPERIENCE / RELIEVING LETTER

Date: {{today}}

To,
The HR Department / Management
{{company_name}}
{{company_address}}

From,
{{employee_name}}
{{employee_address}}

Subject: Demand for issuance of Experience Letter and Relieving Letter

Sir/Madam,

I, {{employee_name}}, was employed at {{company_name}} as {{designation}} from {{joining_date}} to {{last_working_date}}.

Despite completion of my tenure and serving the required notice period, the company has failed to issue me the Experience Letter and Relieving Letter. The details are as follows:

{{reason_for_demand}}

LEGAL POSITION:

1. Under the Industrial Employment (Standing Orders) Act, 1946, an employer is obligated to provide service certificates to employees upon termination or resignation.

2. Withholding of experience/relieving letter without valid reason amounts to unfair labour practice and is actionable before the Labour Court.

3. Such withholding causes direct harm to my career prospects and livelihood.

DEMAND:

You are hereby called upon to issue the following within 15 days of receipt of this notice:

(a) Experience Letter mentioning my designation, period of employment, and conduct
(b) Relieving Letter confirming acceptance of my resignation and relieving from duties
(c) Full and Final Settlement statement (if pending)

Failure to comply within the said period will compel me to approach the Labour Commissioner / Labour Court for appropriate relief, including compensation for the loss suffered.

{{employee_name}}

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `अनुभव / कार्यमुक्ति पत्र हेतु मांग नोटिस

दिनांक: {{today}}

सेवा में,
मानव संसाधन विभाग / प्रबंधन
{{company_name}}
{{company_address}}

प्रेषक,
{{employee_name}}
{{employee_address}}

विषय: अनुभव पत्र एवं कार्यमुक्ति पत्र जारी करने की मांग

महोदय/महोदया,

मैं, {{employee_name}}, {{company_name}} में {{designation}} के पद पर {{joining_date}} से {{last_working_date}} तक कार्यरत था/थी।

अपनी सेवा अवधि पूर्ण करने एवं आवश्यक नोटिस अवधि देने के बावजूद, कम्पनी ने मुझे अनुभव पत्र एवं कार्यमुक्ति पत्र जारी नहीं किया है। विवरण इस प्रकार है:

{{reason_for_demand}}

कानूनी स्थिति:

1. औद्योगिक रोजगार (स्थायी आदेश) अधिनियम, 1946 के तहत, नियोक्ता कर्मचारी की सेवा समाप्ति या त्यागपत्र पर सेवा प्रमाण पत्र देने को बाध्य है।

2. बिना वैध कारण अनुभव/कार्यमुक्ति पत्र रोकना अनुचित श्रम प्रथा है और श्रम न्यायालय के समक्ष कार्रवाई योग्य है।

3. इस प्रकार रोकने से मेरी कैरियर संभावनाओं एवं आजीविका को सीधा नुकसान होता है।

मांग:

आपको इस नोटिस की प्राप्ति के 15 दिनों के भीतर निम्नलिखित जारी करने का आह्वान किया जाता है:

(क) अनुभव पत्र जिसमें मेरा पदनाम, सेवा अवधि एवं आचरण का उल्लेख हो
(ख) कार्यमुक्ति पत्र जो मेरे त्यागपत्र की स्वीकृति एवं कर्तव्यों से मुक्ति की पुष्टि करे
(ग) पूर्ण एवं अंतिम निपटान विवरण (यदि लम्बित है)

निर्धारित अवधि में अनुपालन न करने पर मैं श्रम आयुक्त / श्रम न्यायालय से उचित राहत एवं हुई हानि की क्षतिपूर्ति हेतु संपर्क करने को बाध्य होऊंगा/होऊंगी।

{{employee_name}}

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "noc-general",
    title: { en: "No Objection Certificate (NOC)", hi: "अनापत्ति प्रमाण पत्र (NOC)" },
    description: { en: "General No Objection Certificate template.", hi: "सामान्य अनापत्ति प्रमाण पत्र टेम्पलेट।" },
    category: "property",
    fields: [
      { id: "issuer_name", label: { en: "Issuer Name (Who is giving NOC)", hi: "जारीकर्ता का नाम (NOC देने वाला)" }, type: "text", required: true },
      { id: "issuer_address", label: { en: "Issuer Address", hi: "जारीकर्ता का पता" }, type: "textarea", required: true },
      { id: "beneficiary_name", label: { en: "Beneficiary Name (In whose favour)", hi: "लाभार्थी का नाम (जिसके पक्ष में)" }, type: "text", required: true },
      { id: "purpose", label: { en: "Purpose of NOC", hi: "NOC का उद्देश्य" }, type: "text", required: true },
      { id: "property_or_subject", label: { en: "Property / Subject Matter", hi: "सम्पत्ति / विषय वस्तु" }, type: "textarea", required: true },
      { id: "conditions", label: { en: "Conditions (if any)", hi: "शर्तें (यदि कोई हो)" }, type: "textarea", required: false },
    ],
    template: {
      en: `NO OBJECTION CERTIFICATE

Date: {{today}}

TO WHOMSOEVER IT MAY CONCERN

This is to certify that I/We, {{issuer_name}}, residing at / having office at {{issuer_address}}, have no objection to the following:

BENEFICIARY: {{beneficiary_name}}

PURPOSE: {{purpose}}

SUBJECT MATTER: {{property_or_subject}}

CONDITIONS:
{{conditions}}

I/We hereby declare that:

1. I/We have no claim, right, title, or interest adverse to {{beneficiary_name}} in respect of the above subject matter.

2. This NOC is issued at the request of {{beneficiary_name}} for the purpose stated above.

3. This NOC is valid from the date of issuance unless revoked in writing.

4. I/We shall not raise any objection or dispute in respect of the above matter in any forum.

ISSUER:

{{issuer_name}}
(Signature)

Date: {{today}}
Place: ___________________

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `अनापत्ति प्रमाण पत्र (NOC)

दिनांक: {{today}}

जिसे भी सम्बन्धित हो

यह प्रमाणित किया जाता है कि मैं/हम, {{issuer_name}}, निवासी / कार्यालय {{issuer_address}}, को निम्नलिखित में कोई आपत्ति नहीं है:

लाभार्थी: {{beneficiary_name}}

उद्देश्य: {{purpose}}

विषय वस्तु: {{property_or_subject}}

शर्तें:
{{conditions}}

मैं/हम एतद्द्वारा घोषित करता/करती हूं/करते हैं कि:

1. उपरोक्त विषय वस्तु के संबंध में {{beneficiary_name}} के विरुद्ध मेरा/हमारा कोई दावा, अधिकार, हक या हित नहीं है।

2. यह NOC {{beneficiary_name}} के अनुरोध पर उपरोक्त उद्देश्य हेतु जारी किया गया है।

3. यह NOC जारी करने की तारीख से तब तक वैध है जब तक लिखित रूप में निरस्त न किया जाए।

4. मैं/हम उपरोक्त मामले के संबंध में किसी भी मंच पर कोई आपत्ति या विवाद नहीं उठाएंगे।

जारीकर्ता:

{{issuer_name}}
(हस्ताक्षर)

दिनांक: {{today}}
स्थान: ___________________

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "loan-recovery-notice",
    title: { en: "Loan / Debt Recovery Notice", hi: "ऋण वसूली नोटिस" },
    description: { en: "Legal notice for recovery of money lent / outstanding debt.", hi: "उधार दी गई राशि / बकाया ऋण की वसूली हेतु कानूनी नोटिस।" },
    category: "finance",
    fields: [
      { id: "creditor_name", label: { en: "Creditor Name (You)", hi: "लेनदार का नाम (आप)" }, type: "text", required: true },
      { id: "creditor_address", label: { en: "Creditor Address", hi: "लेनदार का पता" }, type: "textarea", required: true },
      { id: "debtor_name", label: { en: "Debtor Name", hi: "ऋणी का नाम" }, type: "text", required: true },
      { id: "debtor_address", label: { en: "Debtor Address", hi: "ऋणी का पता" }, type: "textarea", required: true },
      { id: "loan_amount", label: { en: "Original Loan Amount (₹)", hi: "मूल ऋण राशि (₹)" }, type: "number", required: true },
      { id: "loan_date", label: { en: "Date of Loan", hi: "ऋण की तारीख" }, type: "date", required: true },
      { id: "outstanding_amount", label: { en: "Outstanding Amount (₹)", hi: "बकाया राशि (₹)" }, type: "number", required: true },
      { id: "interest_rate", label: { en: "Interest Rate (% per annum)", hi: "ब्याज दर (% प्रति वर्ष)" }, type: "text", required: true },
      { id: "deadline_days", label: { en: "Payment Deadline (days)", hi: "भुगतान की समय सीमा (दिन)" }, type: "number", required: true },
    ],
    template: {
      en: `LEGAL NOTICE FOR RECOVERY OF DEBT

Date: {{today}}

To,
{{debtor_name}}
{{debtor_address}}

From,
{{creditor_name}}
{{creditor_address}}

Subject: Legal demand for repayment of outstanding loan of ₹{{outstanding_amount}}

NOTICE

Under instructions from {{creditor_name}}, I hereby serve upon you the following legal notice:

1. That on {{loan_date}}, my client {{creditor_name}} advanced a sum of ₹{{loan_amount}} (Rupees {{loan_amount}} only) to you on the understanding that you would repay the same within the agreed period along with interest at the rate of {{interest_rate}}% per annum.

2. That despite repeated requests and reminders, you have failed to repay the said amount. The total outstanding amount as on date, including principal and accrued interest, stands at ₹{{outstanding_amount}} (Rupees {{outstanding_amount}} only).

3. Your failure to repay the said amount constitutes a breach of trust and the agreement between the parties. My client reserves the right to initiate civil proceedings for recovery of the debt along with interest, costs, and damages.

DEMAND:

You are hereby called upon to pay the outstanding sum of ₹{{outstanding_amount}} along with accrued interest within {{deadline_days}} days from the date of receipt of this notice.

Failing compliance, my client shall be constrained to initiate appropriate legal proceedings against you for recovery of the said amount along with future interest, litigation costs, and damages, at your risk, cost, and consequences.

This notice is issued without prejudice to any other rights and remedies available to my client under law.

{{creditor_name}}

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `ऋण वसूली हेतु कानूनी नोटिस

दिनांक: {{today}}

सेवा में,
{{debtor_name}}
{{debtor_address}}

प्रेषक,
{{creditor_name}}
{{creditor_address}}

विषय: ₹{{outstanding_amount}} के बकाया ऋण की पुनर्भुगतान की कानूनी मांग

नोटिस

{{creditor_name}} के निर्देशानुसार, आपको निम्नलिखित कानूनी नोटिस दिया जाता है:

1. दिनांक {{loan_date}} को मेरे मुवक्किल {{creditor_name}} ने आपको ₹{{loan_amount}} (रुपये {{loan_amount}} मात्र) की राशि इस समझ पर दी थी कि आप निर्धारित अवधि में {{interest_rate}}% प्रति वर्ष ब्याज सहित वापस करेंगे।

2. बार-बार अनुरोध एवं स्मरण कराने के बावजूद, आपने उक्त राशि वापस नहीं की है। आज की तारीख तक मूलधन एवं उपार्जित ब्याज सहित कुल बकाया राशि ₹{{outstanding_amount}} (रुपये {{outstanding_amount}} मात्र) है।

3. उक्त राशि वापस न करना पक्षों के बीच विश्वासभंग एवं समझौते का उल्लंघन है। मेरे मुवक्किल ब्याज, लागत एवं हर्जाने सहित ऋण वसूली हेतु दीवानी कार्यवाही का अधिकार सुरक्षित रखते हैं।

मांग:

आपको इस नोटिस की प्राप्ति से {{deadline_days}} दिनों के भीतर ₹{{outstanding_amount}} की बकाया राशि उपार्जित ब्याज सहित चुकाने का आह्वान किया जाता है।

अनुपालन न करने पर, मेरे मुवक्किल आपके विरुद्ध उक्त राशि, भविष्य का ब्याज, वाद व्यय एवं हर्जाना वसूली हेतु उचित कानूनी कार्यवाही शुरू करने को बाध्य होंगे।

यह नोटिस मेरे मुवक्किल के विधि के तहत उपलब्ध अन्य सभी अधिकारों एवं उपचारों पर प्रतिकूल प्रभाव डाले बिना जारी किया गया है।

{{creditor_name}}

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "housing-society-complaint",
    title: { en: "Housing Society / RWA Complaint", hi: "हाउसिंग सोसायटी / RWA शिकायत" },
    description: { en: "Formal complaint to housing society or Resident Welfare Association.", hi: "हाउसिंग सोसायटी या निवासी कल्याण संघ को औपचारिक शिकायत।" },
    category: "property",
    fields: [
      { id: "complainant_name", label: { en: "Your Name", hi: "आपका नाम" }, type: "text", required: true },
      { id: "flat_number", label: { en: "Flat / House Number", hi: "फ्लैट / मकान नम्बर" }, type: "text", required: true },
      { id: "society_name", label: { en: "Society / RWA Name", hi: "सोसायटी / RWA का नाम" }, type: "text", required: true },
      { id: "society_address", label: { en: "Society Address", hi: "सोसायटी का पता" }, type: "textarea", required: true },
      { id: "complaint_against", label: { en: "Complaint Against (Person / Committee)", hi: "शिकायत किसके विरुद्ध (व्यक्ति / समिति)" }, type: "text", required: true },
      { id: "issue_description", label: { en: "Describe the Issue in Detail", hi: "समस्या का विस्तार से वर्णन करें" }, type: "textarea", required: true },
      { id: "relief_sought", label: { en: "Relief / Action Sought", hi: "मांगी गई राहत / कार्रवाई" }, type: "textarea", required: true },
    ],
    template: {
      en: `FORMAL COMPLAINT TO HOUSING SOCIETY / RWA

Date: {{today}}

To,
The President / Secretary
{{society_name}}
{{society_address}}

From,
{{complainant_name}}
Flat / House No.: {{flat_number}}
{{society_name}}

Subject: Formal complaint regarding {{complaint_against}}

Respected Sir/Madam,

I, {{complainant_name}}, am a bonafide member/resident of {{society_name}}, residing at Flat/House No. {{flat_number}}.

I wish to bring to your kind attention the following grievance:

COMPLAINT AGAINST: {{complaint_against}}

DETAILS OF THE ISSUE:

{{issue_description}}

LEGAL PROVISIONS:

1. As per the applicable Cooperative Societies Act / Apartment Ownership Act of the state, the managing committee/RWA is duty-bound to maintain common areas, ensure transparent governance, and redress member grievances.

2. Under the bye-laws of the society, every member has the right to raise complaints and receive a response within a reasonable timeframe.

3. Failure to address legitimate grievances may compel me to approach the Registrar of Cooperative Societies / District Consumer Forum / competent civil court.

RELIEF SOUGHT:

{{relief_sought}}

I request that this complaint be acknowledged in writing and placed before the next managing committee meeting for resolution. Kindly take corrective action within 30 days.

Thanking you,

{{complainant_name}}
Flat No.: {{flat_number}}

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `हाउसिंग सोसायटी / RWA को औपचारिक शिकायत

दिनांक: {{today}}

सेवा में,
अध्यक्ष / सचिव
{{society_name}}
{{society_address}}

प्रेषक,
{{complainant_name}}
फ्लैट / मकान नम्बर: {{flat_number}}
{{society_name}}

विषय: {{complaint_against}} के संबंध में औपचारिक शिकायत

माननीय महोदय/महोदया,

मैं, {{complainant_name}}, {{society_name}} का/की वास्तविक सदस्य/निवासी हूं, फ्लैट/मकान नम्बर {{flat_number}} में निवास करता/करती हूं।

मैं आपके ध्यान में निम्नलिखित शिकायत लाना चाहता/चाहती हूं:

शिकायत किसके विरुद्ध: {{complaint_against}}

समस्या का विवरण:

{{issue_description}}

कानूनी प्रावधान:

1. राज्य के लागू सहकारी समिति अधिनियम / अपार्टमेंट स्वामित्व अधिनियम के अनुसार, प्रबंध समिति/RWA सामान्य क्षेत्रों के रखरखाव, पारदर्शी शासन सुनिश्चित करने एवं सदस्यों की शिकायतों का निवारण करने के लिए बाध्य है।

2. सोसायटी के उप-नियमों के तहत, प्रत्येक सदस्य को शिकायत उठाने एवं उचित समय सीमा में जवाब प्राप्त करने का अधिकार है।

3. वैध शिकायतों का समाधान न करने पर मैं सहकारी समिति रजिस्ट्रार / जिला उपभोक्ता फोरम / सक्षम दीवानी न्यायालय में जाने को बाध्य हो सकता/सकती हूं।

मांगी गई राहत:

{{relief_sought}}

मैं अनुरोध करता/करती हूं कि इस शिकायत को लिखित रूप में स्वीकार किया जाए एवं समाधान हेतु अगली प्रबंध समिति बैठक में प्रस्तुत किया जाए। कृपया 30 दिनों के भीतर सुधारात्मक कार्रवाई करें।

धन्यवाद,

{{complainant_name}}
फ्लैट नम्बर: {{flat_number}}

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "medical-negligence-complaint",
    title: { en: "Medical Negligence Complaint", hi: "चिकित्सा लापरवाही शिकायत" },
    description: { en: "Complaint against hospital/doctor for medical negligence or malpractice.", hi: "चिकित्सा लापरवाही या कदाचार के लिए अस्पताल/डॉक्टर के विरुद्ध शिकायत।" },
    category: "consumer",
    fields: [
      { id: "patient_name", label: { en: "Patient Name", hi: "रोगी का नाम" }, type: "text", required: true },
      { id: "patient_address", label: { en: "Patient Address", hi: "रोगी का पता" }, type: "textarea", required: true },
      { id: "hospital_name", label: { en: "Hospital / Clinic Name", hi: "अस्पताल / क्लिनिक का नाम" }, type: "text", required: true },
      { id: "hospital_address", label: { en: "Hospital Address", hi: "अस्पताल का पता" }, type: "textarea", required: true },
      { id: "doctor_name", label: { en: "Doctor Name", hi: "डॉक्टर का नाम" }, type: "text", required: true },
      { id: "treatment_date", label: { en: "Date of Treatment", hi: "उपचार की तारीख" }, type: "date", required: true },
      { id: "treatment_description", label: { en: "Treatment Given", hi: "दिया गया उपचार" }, type: "textarea", required: true },
      { id: "negligence_description", label: { en: "How was the doctor/hospital negligent?", hi: "डॉक्टर/अस्पताल ने कैसे लापरवाही की?" }, type: "textarea", required: true },
      { id: "damages_amount", label: { en: "Compensation Claimed (₹)", hi: "मांगी गई क्षतिपूर्ति (₹)" }, type: "number", required: true },
    ],
    template: {
      en: `COMPLAINT FOR MEDICAL NEGLIGENCE

Date: {{today}}

To,
The District Consumer Disputes Redressal Commission
[District & State]

Complainant:
{{patient_name}}
{{patient_address}}

Versus

Opposite Party 1: {{doctor_name}}
Opposite Party 2: {{hospital_name}}, {{hospital_address}}

COMPLAINT UNDER SECTION 35 OF THE CONSUMER PROTECTION ACT, 2019

1. The complainant {{patient_name}} is a "consumer" as defined under Section 2(7) of the Consumer Protection Act, 2019, having availed medical services from the Opposite Parties.

2. The complainant approached {{hospital_name}} and was treated by Dr. {{doctor_name}} on {{treatment_date}}.

3. TREATMENT GIVEN:
{{treatment_description}}

4. NEGLIGENCE:
The Opposite Parties were negligent in the following manner:
{{negligence_description}}

5. LEGAL PROVISIONS:
(a) Under Section 2(42) of the Consumer Protection Act, 2019, "service" includes medical/healthcare services. Medical negligence constitutes "deficiency in service."
(b) The Hon'ble Supreme Court in Indian Medical Association v. V.P. Shantha (1995) held that medical services fall within the ambit of the Consumer Protection Act.
(c) A medical practitioner owes a duty of care to the patient, and breach of this duty resulting in injury constitutes actionable negligence.

6. RELIEF SOUGHT:
(a) Compensation of ₹{{damages_amount}} for medical negligence, pain and suffering, loss of income, and additional medical expenses
(b) Cost of future treatment and rehabilitation
(c) Cost of litigation
(d) Any other relief deemed fit by this Hon'ble Commission

VERIFICATION:
I, {{patient_name}}, verify that the above contents are true to the best of my knowledge and belief.

{{patient_name}}
Date: {{today}}

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `चिकित्सा लापरवाही हेतु शिकायत

दिनांक: {{today}}

सेवा में,
जिला उपभोक्ता विवाद निवारण आयोग
[जिला एवं राज्य]

परिवादी:
{{patient_name}}
{{patient_address}}

बनाम

विपक्षी 1: {{doctor_name}}
विपक्षी 2: {{hospital_name}}, {{hospital_address}}

उपभोक्ता संरक्षण अधिनियम, 2019 की धारा 35 के तहत शिकायत

1. परिवादी {{patient_name}} उपभोक्ता संरक्षण अधिनियम, 2019 की धारा 2(7) में परिभाषित "उपभोक्ता" है, जिसने विपक्षियों से चिकित्सा सेवाएं प्राप्त कीं।

2. परिवादी ने {{hospital_name}} में संपर्क किया और डॉ. {{doctor_name}} द्वारा {{treatment_date}} को उपचार किया गया।

3. दिया गया उपचार:
{{treatment_description}}

4. लापरवाही:
विपक्षियों ने निम्नलिखित प्रकार से लापरवाही की:
{{negligence_description}}

5. कानूनी प्रावधान:
(क) उपभोक्ता संरक्षण अधिनियम, 2019 की धारा 2(42) के तहत, "सेवा" में चिकित्सा/स्वास्थ्य सेवाएं सम्मिलित हैं। चिकित्सा लापरवाही "सेवा में कमी" है।
(ख) माननीय सर्वोच्च न्यायालय ने इंडियन मेडिकल एसोसिएशन बनाम वी.पी. शांता (1995) में निर्णय दिया कि चिकित्सा सेवाएं उपभोक्ता संरक्षण अधिनियम के दायरे में आती हैं।
(ग) चिकित्सक का रोगी के प्रति देखभाल का कर्तव्य है, और इस कर्तव्य का उल्लंघन जिससे क्षति हो, कार्रवाई योग्य लापरवाही है।

6. मांगी गई राहत:
(क) चिकित्सा लापरवाही, पीड़ा, आय की हानि एवं अतिरिक्त चिकित्सा व्यय हेतु ₹{{damages_amount}} की क्षतिपूर्ति
(ख) भविष्य के उपचार एवं पुनर्वास की लागत
(ग) वाद व्यय
(घ) कोई अन्य राहत जो यह माननीय आयोग उचित समझे

सत्यापन:
मैं, {{patient_name}}, सत्यापित करता/करती हूं कि उपरोक्त विषय-वस्तु मेरी जानकारी एवं विश्वास के अनुसार सत्य है।

{{patient_name}}
दिनांक: {{today}}

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "dowry-complaint",
    title: { en: "Dowry Harassment Complaint", hi: "दहेज उत्पीड़न शिकायत" },
    description: { en: "Complaint for dowry demand and harassment under Dowry Prohibition Act and S.498A IPC.", hi: "दहेज निषेध अधिनियम एवं धारा 498A IPC के तहत दहेज मांग एवं उत्पीड़न की शिकायत।" },
    category: "family",
    fields: [
      { id: "complainant_name", label: { en: "Your Name (Wife / Her Relative)", hi: "आपका नाम (पत्नी / उसका रिश्तेदार)" }, type: "text", required: true },
      { id: "complainant_address", label: { en: "Your Address", hi: "आपका पता" }, type: "textarea", required: true },
      { id: "husband_name", label: { en: "Husband's Name", hi: "पति का नाम" }, type: "text", required: true },
      { id: "in_laws_names", label: { en: "In-laws' Names (Father-in-law, Mother-in-law, etc.)", hi: "ससुराल वालों के नाम (ससुर, सास, आदि)" }, type: "textarea", required: true },
      { id: "marriage_date", label: { en: "Date of Marriage", hi: "विवाह की तारीख" }, type: "date", required: true },
      { id: "dowry_demands", label: { en: "Details of Dowry Demands", hi: "दहेज मांगों का विवरण" }, type: "textarea", required: true },
      { id: "harassment_description", label: { en: "Details of Harassment / Cruelty", hi: "उत्पीड़न / क्रूरता का विवरण" }, type: "textarea", required: true },
    ],
    template: {
      en: `COMPLAINT FOR DOWRY HARASSMENT

Date: {{today}}

To,
The Station House Officer
[Police Station Name & Address]

From,
{{complainant_name}}
{{complainant_address}}

Subject: Complaint under Dowry Prohibition Act, 1961 and Section 498A of IPC / Section 85-86 of BNS

Respected Sir/Madam,

I, {{complainant_name}}, submit this complaint against the following persons for dowry demand, dowry harassment, and cruelty:

ACCUSED PERSONS:
1. {{husband_name}} (Husband)
2. {{in_laws_names}}

FACTS:

1. I was married to {{husband_name}} on {{marriage_date}}.

2. DOWRY DEMANDS:
{{dowry_demands}}

3. HARASSMENT AND CRUELTY:
{{harassment_description}}

LEGAL PROVISIONS:

1. The demand of dowry is an offence under Section 3 and Section 4 of the Dowry Prohibition Act, 1961, punishable with imprisonment of not less than 5 years and fine of not less than ₹15,000 or the amount of dowry demanded, whichever is more.

2. The harassment and cruelty by the husband and his relatives constitutes an offence under Section 498A of the Indian Penal Code (corresponding to Section 85-86 of BNS), punishable with imprisonment up to 3 years and fine.

3. The accused persons are also liable under Section 3/4 of the Dowry Prohibition Act for giving, taking, and demanding dowry.

PRAYER:

I pray that:
(a) An FIR be registered against all accused persons under the above-mentioned provisions
(b) The matter be investigated thoroughly
(c) Appropriate action be taken against the accused persons as per law

I am ready to provide any further information and evidence as required.

{{complainant_name}}
(Signature)

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `दहेज उत्पीड़न शिकायत

दिनांक: {{today}}

सेवा में,
थाना प्रभारी
[थाने का नाम एवं पता]

प्रेषक,
{{complainant_name}}
{{complainant_address}}

विषय: दहेज निषेध अधिनियम, 1961 एवं IPC की धारा 498A / BNS की धारा 85-86 के तहत शिकायत

माननीय महोदय/महोदया,

मैं, {{complainant_name}}, निम्नलिखित व्यक्तियों के विरुद्ध दहेज मांग, दहेज उत्पीड़न एवं क्रूरता की शिकायत प्रस्तुत करती हूं:

आरोपी व्यक्ति:
1. {{husband_name}} (पति)
2. {{in_laws_names}}

तथ्य:

1. मेरा विवाह {{husband_name}} से दिनांक {{marriage_date}} को हुआ था।

2. दहेज की मांगें:
{{dowry_demands}}

3. उत्पीड़न एवं क्रूरता:
{{harassment_description}}

कानूनी प्रावधान:

1. दहेज की मांग दहेज निषेध अधिनियम, 1961 की धारा 3 एवं धारा 4 के तहत अपराध है, जो कम से कम 5 वर्ष के कारावास एवं कम से कम ₹15,000 या मांगी गई दहेज राशि, जो भी अधिक हो, के जुर्माने से दण्डनीय है।

2. पति एवं उसके रिश्तेदारों द्वारा उत्पीड़न एवं क्रूरता भारतीय दण्ड संहिता की धारा 498A (BNS की धारा 85-86 के तदनुरूप) के तहत अपराध है, जो 3 वर्ष तक के कारावास एवं जुर्माने से दण्डनीय है।

3. आरोपी व्यक्ति दहेज निषेध अधिनियम की धारा 3/4 के तहत दहेज लेने एवं मांगने के लिए भी उत्तरदायी हैं।

प्रार्थना:

मैं प्रार्थना करती हूं कि:
(क) सभी आरोपी व्यक्तियों के विरुद्ध उपरोक्त प्रावधानों के तहत FIR दर्ज की जाए
(ख) मामले की गहन जांच की जाए
(ग) आरोपी व्यक्तियों के विरुद्ध विधि अनुसार उचित कार्रवाई की जाए

मैं आवश्यकतानुसार कोई भी अतिरिक्त जानकारी एवं साक्ष्य देने को तैयार हूं।

{{complainant_name}}
(हस्ताक्षर)

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
  {
    id: "early-hearing-application",
    title: { en: "Application for Early / Urgent Hearing", hi: "शीघ्र / अविलम्ब सुनवाई हेतु आवेदन" },
    description: { en: "Application to court for early or urgent hearing of a pending case.", hi: "लम्बित मामले की शीघ्र या अविलम्ब सुनवाई हेतु न्यायालय में आवेदन।" },
    category: "legal",
    fields: [
      { id: "applicant_name", label: { en: "Applicant Name", hi: "आवेदक का नाम" }, type: "text", required: true },
      { id: "case_number", label: { en: "Case Number", hi: "मामला संख्या" }, type: "text", required: true },
      { id: "court_name", label: { en: "Court Name", hi: "न्यायालय का नाम" }, type: "text", required: true },
      { id: "opposite_party", label: { en: "Opposite Party Name", hi: "विपक्षी का नाम" }, type: "text", required: true },
      { id: "reason_for_urgency", label: { en: "Reason for Urgency", hi: "अविलम्बता का कारण" }, type: "textarea", required: true },
    ],
    template: {
      en: `IN THE COURT OF {{court_name}}

Case No.: {{case_number}}

{{applicant_name}} ... Applicant / Petitioner / Plaintiff
Versus
{{opposite_party}} ... Respondent / Defendant

APPLICATION FOR EARLY / URGENT HEARING

MOST RESPECTFULLY SHOWETH:

1. That the above-titled case is pending before this Hon'ble Court.

2. That the applicant {{applicant_name}} most respectfully submits this application for early/urgent hearing of the above case on the following grounds:

GROUNDS FOR URGENCY:

{{reason_for_urgency}}

3. That unless this matter is heard on an urgent basis, the applicant shall suffer irreparable loss and injury, and the very purpose of the proceedings shall be defeated.

4. That no prejudice shall be caused to the opposite party if the matter is taken up for early hearing.

5. That this application is being made bonafide and in the interest of justice.

PRAYER:

It is most respectfully prayed that this Hon'ble Court may be pleased to:

(a) Allow this application for early hearing;
(b) Fix the above-titled case for hearing on an early date;
(c) Pass any other order deemed fit and proper in the interest of justice.

APPLICANT

{{applicant_name}}

Date: {{today}}
Through Counsel: ___________________

---
Template generated by NyayCheck. Consult a lawyer before using.`,
      hi: `न्यायालय {{court_name}} में

मामला संख्या: {{case_number}}

{{applicant_name}} ... आवेदक / याचिकाकर्ता / वादी
बनाम
{{opposite_party}} ... प्रतिवादी / प्रत्यर्थी

शीघ्र / अविलम्ब सुनवाई हेतु आवेदन

सविनय निवेदन है कि:

1. उपरोक्त मामला इस माननीय न्यायालय के समक्ष लम्बित है।

2. आवेदक {{applicant_name}} सविनय निम्नलिखित आधारों पर उपरोक्त मामले की शीघ्र/अविलम्ब सुनवाई हेतु यह आवेदन प्रस्तुत करता/करती है:

अविलम्बता के आधार:

{{reason_for_urgency}}

3. जब तक इस मामले की अविलम्ब सुनवाई नहीं होती, आवेदक को अपूरणीय हानि एवं क्षति होगी, और कार्यवाही का उद्देश्य ही विफल हो जाएगा।

4. यदि मामले की शीघ्र सुनवाई की जाती है तो विपक्षी को कोई प्रतिकूलता नहीं होगी।

5. यह आवेदन सद्भावपूर्वक एवं न्याय हित में किया जा रहा है।

प्रार्थना:

सविनय प्रार्थना है कि यह माननीय न्यायालय कृपया:

(क) शीघ्र सुनवाई हेतु इस आवेदन को स्वीकार करें;
(ख) उपरोक्त मामले को शीघ्र तारीख पर सुनवाई हेतु नियत करें;
(ग) न्याय हित में कोई अन्य उचित आदेश पारित करें।

आवेदक

{{applicant_name}}

दिनांक: {{today}}
अधिवक्ता द्वारा: ___________________

---
NyayCheck द्वारा जनरेट टेम्पलेट। उपयोग से पहले वकील से परामर्श करें।`,
    },
  },
];

export function getTemplateById(id: string): DocumentTemplate | undefined {
  return documentTemplates.find((t) => t.id === id);
}
